mutation PruneNav {
  menuUpdate(id: "gid://shopify/Menu/248882266339", title: "Main menu", handle: "main-menu", items: [
    {id: "gid://shopify/MenuItem/617904832739", title: "Shop All", type: COLLECTION, resourceId: "gid://shopify/Collection/465922326755"},
    {id: "gid://shopify/MenuItem/617904865507", title: "Guys", type: COLLECTION, resourceId: "gid://shopify/Collection/471526441187"},
    {id: "gid://shopify/MenuItem/617904898275", title: "Girls", type: COLLECTION, resourceId: "gid://shopify/Collection/471526473955"},
    {id: "gid://shopify/MenuItem/617904931043", title: "Youth", type: COLLECTION, resourceId: "gid://shopify/Collection/471526506723"},
    {id: "gid://shopify/MenuItem/617904963811", title: "Home & Living", type: COLLECTION, resourceId: "gid://shopify/Collection/471526572259"},
    {id: "gid://shopify/MenuItem/617904996579", title: "Accessories", type: COLLECTION, resourceId: "gid://shopify/Collection/471526605027"},
    {id: "gid://shopify/MenuItem/617905029347", title: "Collections", type: HTTP, url: "/collections", items: [
      {id: "gid://shopify/MenuItem/620481315043", title: "Bundles & Vaults", type: COLLECTION, resourceId: "gid://shopify/Collection/472495718627"},
      {id: "gid://shopify/MenuItem/617905062115", title: "Maximalist Motifs", type: COLLECTION, resourceId: "gid://shopify/Collection/465923506403"},
      {id: "gid://shopify/MenuItem/617905094883", title: "Cognitive Drift", type: COLLECTION, resourceId: "gid://shopify/Collection/469695627491"},
      {id: "gid://shopify/MenuItem/617905127651", title: "Boundless Bleeds", type: COLLECTION, resourceId: "gid://shopify/Collection/465917903075"},
      {id: "gid://shopify/MenuItem/617905160419", title: "Primal Prints", type: COLLECTION, resourceId: "gid://shopify/Collection/465920983267"},
      {id: "gid://shopify/MenuItem/617905193187", title: "StreetsmART", type: COLLECTION, resourceId: "gid://shopify/Collection/465877958883"},
      {id: "gid://shopify/MenuItem/617905225955", title: "Static Frequency", type: COLLECTION, resourceId: "gid://shopify/Collection/466686247139"},
      {id: "gid://shopify/MenuItem/617905258723", title: "Avant-Kindergarden™", type: COLLECTION, resourceId: "gid://shopify/Collection/466692702435"},
      {id: "gid://shopify/MenuItem/617905291491", title: "Tacticolor", type: COLLECTION, resourceId: "gid://shopify/Collection/465921147107"},
      {id: "gid://shopify/MenuItem/617905324259", title: "Ocular Opulence", type: COLLECTION, resourceId: "gid://shopify/Collection/468221690083"},
      {id: "gid://shopify/MenuItem/617905357027", title: "Transcendent Artifacts", type: COLLECTION, resourceId: "gid://shopify/Collection/468252852451"},
      {id: "gid://shopify/MenuItem/617905389795", title: "Chromatic Overload", type: COLLECTION, resourceId: "gid://shopify/Collection/469695496419"},
      {id: "gid://shopify/MenuItem/617905422563", title: "Hyperdensity", type: COLLECTION, resourceId: "gid://shopify/Collection/469695529187"},
      {id: "gid://shopify/MenuItem/617905455331", title: "Color Riot", type: COLLECTION, resourceId: "gid://shopify/Collection/469695561955"},
      {id: "gid://shopify/MenuItem/617905488099", title: "Astral Syntax", type: COLLECTION, resourceId: "gid://shopify/Collection/469695660259"},
      {id: "gid://shopify/MenuItem/617905520867", title: "Cosmic Debris", type: COLLECTION, resourceId: "gid://shopify/Collection/469695693027"},
      {id: "gid://shopify/MenuItem/617905553635", title: "Quantum Bloom", type: COLLECTION, resourceId: "gid://shopify/Collection/469695758563"},
      {id: "gid://shopify/MenuItem/617905586403", title: "Vibe-Checked Vectors", type: COLLECTION, resourceId: "gid://shopify/Collection/469518024931"}
    ]},
    {id: "gid://shopify/MenuItem/626070454499", title: "FAQ", type: PAGE, resourceId: "gid://shopify/Page/129268351203"}
  ]) {
    menu { id items { title url items { title } } }
    userErrors { field message }
  }
}