import { Helmet } from "react-helmet-async";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { Link } from "react-router-dom";
import "./live-visuals.css";

const offerings = [
  { number:"01", title:"Live visual performance", copy:"Audio-reactive visuals performed in the room—not a playlist left running. A responsive visual language for concerts, DJ sets, festivals, galleries, launch events, and rooms that deserve more than a screen saver.", tags:"VJ PERFORMANCE · REAL-TIME FX · SHOW CONTROL" },
  { number:"02", title:"Tour & stage visuals", copy:"Custom concert visuals, LED wall content, VJ loops, transitions, interludes, and show packages built around the emotional architecture of your set. Scalable for clubs, theaters, festival stages, and projection surfaces.", tags:"TOUR VISUALS · LED CONTENT · VJ LOOPS" },
  { number:"03", title:"YouTube & livestream worlds", copy:"Long-form visual systems for YouTube music channels, Twitch streams, listening rooms, radio stations, album premieres, and 24/7 live streams—designed to hold attention without fighting the music.", tags:"YOUTUBE VISUALS · OBS · LIVESTREAM DESIGN" },
  { number:"04", title:"Music videos & release assets", copy:"Glitch music videos, audio-reactive visualizers, Spotify Canvas loops, vertical clips, teasers, cover motion, and social cutdowns that make one release feel like a whole visual universe.", tags:"MUSIC VISUALIZER · SPOTIFY CANVAS · SOCIAL VIDEO" },
  { number:"05", title:"Projection & installations", copy:"Generative projection content and immersive visuals for architecture, pop-ups, fashion, art spaces, brand activations, and unconventional canvases. Built to bend around the place it lives.", tags:"PROJECTION MAPPING · INSTALLATION ART · IMMERSIVE MEDIA" },
  { number:"06", title:"Creative direction & systems", copy:"A cohesive moving-image identity: visual research, concept development, motion language, generative systems, and repeatable content engines for artists and teams who need more than a one-off clip.", tags:"CREATIVE DIRECTION · GENERATIVE ART · VISUAL IDENTITY" },
];
const socials = [
  ["Instagram","https://instagram.com/aestheticrebellion"], ["X / Twitter","https://twitter.com/aestheticrebel"],
  ["SoundCloud","https://soundcloud.com/aestheticrebel"], ["GitHub","https://github.com/Mlswchr75"],
  ["LinkedIn","https://linkedin.com/in/myleswhitcher"], ["Reddit","https://www.reddit.com/user/Emotional-Goat1086/"],
  ["Pinterest","https://www.pinterest.com/aestheticrebellion/"], ["Telegram","https://t.me/dylesmavis"],
];
const keywordCloud = ["audio-reactive visuals","concert visuals","tour visuals","live VJ","generative art","projection mapping","music visualizer","LED wall content","glitch art","datamosh video","livestream visuals","YouTube visualizer","Twitch visuals","immersive installation","real-time graphics","Spotify Canvas","festival visuals","visual identity","experimental film","creative coding","WebGL","shader art","motion design","OBS visuals"];

const VisualField = ({ compact=false }:{ compact?:boolean }) => <div className={`lv-field ${compact?"lv-field--compact":""}`} aria-hidden="true"><div className="lv-orbit lv-orbit--one"/><div className="lv-orbit lv-orbit--two"/><div className="lv-orbit lv-orbit--three"/><div className="lv-core"/><div className="lv-scan lv-scan--a"/><div className="lv-scan lv-scan--b"/></div>;

const LiveVisuals = () => {
  const title="Live Visuals, Tour Content & Music Visualizers — MOSH";
  const description="Custom audio-reactive concert visuals, tour content, projection mapping, VJ loops, YouTube livestream visuals, music visualizers, and generative visual systems by Dyles Mavis and Aesthetic Rebellion.";
  const canonical="https://ether-mosh.online/live-visuals";
  return <main className="lv-page">
    <Helmet><title>{title}</title><meta name="description" content={description}/><meta name="keywords" content="live visuals, concert visuals, tour visuals, VJ loops, projection mapping, music visualizer, audio reactive visuals, generative visuals, LED wall content, YouTube livestream visuals, Twitch visuals, Spotify Canvas, visual artist"/><link rel="canonical" href={canonical}/><meta property="og:title" content={title}/><meta property="og:description" content={description}/><meta property="og:url" content={canonical}/><meta property="og:image" content="https://ether-mosh.online/og-image.png"/><meta property="og:type" content="website"/><script type="application/ld+json">{JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:"MOSH by Aesthetic Rebellion",url:canonical,email:["dyles@aestheticrebellion.store","myleswhitcher@gmail.com"],founder:{"@type":"Person",name:"Dyles Mavis"},areaServed:"Worldwide",description,knowsAbout:keywordCloud,sameAs:socials.map(([,href])=>href)})}</script></Helmet>
    <header className="lv-nav"><Link to="/" className="lv-mark" aria-label="MOSH home">M<span>O</span>SH</Link><nav aria-label="Page navigation"><a href="#about">About</a><a href="#offerings">Offerings</a><a href="#dyles">Dyles</a><a href="#contact">Contact</a></nav><a href="mailto:dyles@aestheticrebellion.store?subject=MOSH%20visuals%20inquiry" className="lv-availability"><i/> Available for select work</a></header>
    <section className="lv-hero"><div className="lv-kicker">Live visuals / tour content / generative systems</div><h1>The screen<br/>should feel<br/>the <em>music.</em></h1><div className="lv-hero-copy"><p>Custom visual worlds for artists, performers, festivals, streams, stages, and beautiful ideas that refuse to sit still.</p><a href="#offerings">See what we make <ArrowDownRight/></a></div><div className="lv-hero-art"><VisualField/></div><span className="lv-index">01 / 05</span></section>
    <section className="lv-section lv-about" id="about"><div className="lv-section-number">02</div><div><div className="lv-kicker">About the instrument</div><h2>MOSH makes<br/>sound visible.</h2></div><div className="lv-about-art"><VisualField compact/></div><div className="lv-prose"><p className="lv-lede">MOSH is an audiovisual performance instrument built for the exact moment a track stops being something you hear and becomes somewhere you are.</p><p>It turns audio, images, video, cameras, patterns, and live decisions into responsive motion. Every frame can react. Every performance can mutate. The machine brings speed; a human still decides what matters.</p><p>Use it live on stage, route it into OBS, build an hour-long YouTube visual, record a music video, generate VJ loops, or let Journey Mode evolve a world while the music keeps moving.</p><Link to="/edit">Open the instrument <ArrowUpRight/></Link></div></section>
    <section className="lv-section lv-offerings" id="offerings"><div className="lv-section-number">03</div><div className="lv-offerings-head"><div className="lv-kicker">Offerings / capabilities</div><h2>Ways to make<br/>the room move.</h2><p>One-off commissions, full visual packages, live collaboration, and scalable systems. Remote worldwide. Built around the song, the space, and what you actually need to deliver.</p></div><div className="lv-service-list">{offerings.map(service=><article className="lv-service" key={service.number}><span>{service.number}</span><div><h3>{service.title}</h3><p>{service.copy}</p><small>{service.tags}</small></div><ArrowUpRight/></article>)}</div></section>
    <section className="lv-section lv-dyles" id="dyles"><div className="lv-section-number">04</div><div className="lv-dyles-title"><div className="lv-kicker">Artist / designer / builder</div><h2>Dyles<br/>Mavis.</h2></div><div className="lv-statement"><span>Founder of</span><strong>Aesthetic<br/>Rebellion</strong></div><div className="lv-prose"><p className="lv-lede">I make tools and images for people who are bored by safe decisions.</p><p>Dyles Mavis is the multidisciplinary artist behind MOSH and Aesthetic Rebellion—a creative practice moving between digital art, filmmaking, generative systems, maximalist pattern, wearable art, real-time graphics, and controlled catastrophe.</p><p>Aesthetic Rebellion is not rebellion for the costume of it. It is a refusal of sterile templates, visual sameness, and the idea that digital work has to behave itself. Glitches become gestures. Artifacts become texture. Chaos becomes authorship.</p><a href="https://aestheticrebellion.store" target="_blank" rel="noreferrer">Visit Aesthetic Rebellion <ArrowUpRight/></a></div></section>
    <section className="lv-section lv-interests"><div className="lv-section-number">05</div><div><div className="lv-kicker">Skills / areas of interest</div><h2>Signal,<br/>noise & nerve.</h2></div><div className="lv-keywords" aria-label="Skills and areas of interest">{keywordCloud.map((keyword,index)=><span key={keyword}><i>{String(index+1).padStart(2,"0")}</i>{keyword}</span>)}</div></section>
    <section className="lv-contact" id="contact"><div className="lv-kicker">Bookings / commissions / strange good ideas</div><h2>Bring me the track.<br/><em>Chaos is the medium.</em></h2><p>If you are an artist, label, creative director, production designer, venue, streamer, festival, brand, or person with a wall that should be doing more—tell me what you are making.</p><div className="lv-emails"><a className="lv-email" href="mailto:dyles@aestheticrebellion.store?subject=MOSH%20visuals%20inquiry">dyles@aestheticrebellion.store <ArrowUpRight/></a><a className="lv-email lv-email--secondary" href="mailto:myleswhitcher@gmail.com?subject=MOSH%20visuals%20inquiry">myleswhitcher@gmail.com <ArrowUpRight/></a></div><div className="lv-socials">{socials.map(([name,href])=><a key={name} href={href} target="_blank" rel="noreferrer">{name}<ArrowUpRight/></a>)}</div></section>
    <footer className="lv-footer"><span>MOSH™ / audiovisual performance instrument</span><span>© 2026 Dyles Mavis · Aesthetic Rebellion</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/">Enter MOSH</Link></div></footer>
  </main>;
};
export default LiveVisuals;
