export type NewsArticle = {
  slug: string;
  subjectKind: "effect" | "mode";
  effectId?: string;
  effectName: string;
  category: string;
  title: string;
  dek: string;
  description: string;
  publishedAt: string;
  readMinutes: number;
  image: string;
  imageAlt: string;
  imageCaption: string;
  keywords: string[];
  tldr: string;
  satireDisclosure: string;
  dispatch: string[];
  explanation: string[];
  steps: string[];
  parameters: { control: string; purpose: string; low: string; high: string; sweetSpot: string }[];
  uses: { title: string; body: string }[];
  quote: string;
  quoteAttribution: string;
  downloadHref: string;
  product: { name: string; href: string; copy: string };
  sources: { label: string; href: string; note: string }[];
  relatedEffects: string[];
  faqs: { question: string; answer: string }[];
};

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    slug: "sort-your-pixels-before-they-sort-you",
    subjectKind: "effect",
    effectId: "pixelSort",
    effectName: "Pixel Sort",
    category: "Effect School",
    title: "Sort Your Pixels Before They Sort You",
    dek: "A practical field guide to brightness-driven smearing, why the internet fell for it, and how to weaponize it without making visual oatmeal.",
    description: "Learn what pixel sorting is, where the glitch-art technique came from, and how to use Ether-MOSH Pixel Sort for video, print, projection, patterns, and motion graphics.",
    publishedAt: "2026-08-31T08:00:00-07:00",
    readMinutes: 6,
    image: "/news/pixel-sort-bureaucracy.jpg",
    imageAlt: "Fictional workers sorting black, white, and magenta pixels beneath a portrait stretched into horizontal pixel-sort streaks",
    imageCaption: "The Department of Pixel Labor denies that brightness has become a caste system. The pixels have retained counsel.",
    keywords: ["pixel sorting", "pixel sort effect", "glitch art", "Ether-MOSH Pixel Sort", "how to pixel sort", "real-time GPU effects"],
    tldr: "Pixel sorting reorders selected pixels along an axis according to brightness or color. Ether-MOSH uses a fast GPU interpretation: Threshold decides which luminance regions move, and Amount decides how far the horizontal smear travels.",
    satireDisclosure: "The department, workers, and labor dispute are fictional. The technique, controls, history, and production advice are real.",
    dispatch: [
      "At 08:14 this morning, the fictional Department of Pixel Labor announced that every bright pixel had been reassigned three hundred columns east. Dark pixels were told to remain calm and stop asking what happened to the cheekbone.",
      "Commissioner Gary Raster—an invented man with the confidence of a printer driver—called the streaking ‘a routine organizational event.’ He is lying. It is pixel sorting, it looks fantastic, and restraint is the only thing keeping your portrait from becoming artisanal horizontal soup.",
    ],
    explanation: [
      "Classic pixel sorting selects runs of pixels using a threshold, orders those pixels by a value such as brightness, and writes them back along a row or column. Kim Asendorf's 2010 ASDFPixelSort Processing script exposed white, black, bright, and dark threshold modes and helped establish the technique's modern visual vocabulary.",
      "Ether-MOSH is built for live performance, so its shader measures luminance, opens a soft gate around Threshold, and applies a noisy horizontal displacement scaled by Amount. You get the recognizable bright-region streaks at interactive speed, with the source still legible underneath.",
    ],
    steps: [
      "Open MOSH, load a high-contrast portrait, skyline, product image, or clip, then open the FX panel.",
      "Choose Data Corruption and add Pixel Sort. Start with Amount near 0.30 and Threshold near 0.55.",
      "Lower Threshold until the important highlights begin to streak. If the whole frame moves, crawl back from the ledge.",
      "Raise Amount for longer travel. Stack RGB Shift or Film Grain after it for separation and texture.",
      "Export a still for print, or record a short loop while animating one control slowly. One deliberate move beats twelve frantic knob confessions.",
    ],
    parameters: [
      { control: "Amount", purpose: "Distance and strength of the horizontal smear", low: "Source stays legible", high: "Long wrapping streaks", sweetSpot: "0.25–0.60" },
      { control: "Threshold", purpose: "Luminance gate deciding which regions move", low: "More of the frame qualifies", high: "Only bright regions qualify", sweetSpot: "0.35–0.65" },
      { control: "Source contrast", purpose: "Separation before the effect", low: "Soft cloudy movement", high: "Crisp streak boundaries", sweetSpot: "Strong subject edges" },
    ],
    uses: [
      { title: "Print + pattern", body: "Build a bold still and test a 3×3 repeat before committing to fabric or wallpaper. Streaks crossing a tile edge can become excellent seams or deeply stupid seams." },
      { title: "Projection + venue", body: "Use faces, architecture, or typography with obvious light-dark structure. Slow Amount changes read across a room; micro-jitter dies on the LED wall." },
      { title: "Vector + Lottie", body: "Pixel Sort is raster by nature. Trace only the strongest streak silhouettes for vector shapes, or feed a short high-contrast loop into a masked Lottie sticker." },
      { title: "Museum + education", body: "Compare MOSH output with the original ASDFPixelSort code to show how literal sorting and shader displacement can share a visual language while using different machinery." },
    ],
    quote: "Pixel sorting is not about destroying the image. It is about revealing the hierarchy the image was already hiding, then shoving that hierarchy sideways.",
    quoteAttribution: "The completely unauthorized MOSH field manual",
    downloadHref: "/news/downloads/pixel-sort-field-card.md",
    product: {
      name: "Liquid Glitch Beanie",
      href: "https://aestheticrebellion.store/products/liquid-glitch-beanie",
      copy: "Mandatory paid interruption: the Liquid Glitch Beanie at aestheticrebellion.store will not improve your threshold decisions. It will, however, make your skull look like it has better layer management. Capitalism has entered the tutorial wearing knitwear.",
    },
    sources: [
      { label: "Kim Asendorf — ASDFPixelSort", href: "https://github.com/kimasendorf/ASDFPixelSort", note: "Original 2010 Processing script and threshold modes." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current effect parameters, descriptions, and GLSL source." },
    ],
    relatedEffects: ["rgbShift", "filmGrain", "halftone", "photocopy"],
    faqs: [
      { question: "Is Ether-MOSH doing literal pixel sorting?", answer: "It is a real-time GPU interpretation. Luminance thresholds and horizontal displacement create the visual language without freezing live playback for a full CPU sort." },
      { question: "What images work best with Pixel Sort?", answer: "High-contrast portraits, architecture, night lights, bold type, and footage with clear silhouettes give the threshold useful structure to grab." },
      { question: "Can I use Pixel Sort for print?", answer: "Yes. Export a high-resolution still, inspect streak edges at 100%, proof the physical size, and use the print-ready 300 DPI export path." },
      { question: "Where is Pixel Sort in Ether-MOSH?", answer: "Open the FX panel, select Data Corruption, and add Pixel Sort. Desktop users can also open the command palette and search for it." },
    ],
  },
  {
    slug: "halftone-is-not-a-phase-mom",
    subjectKind: "effect",
    effectId: "halftone",
    effectName: "Halftone",
    category: "Print Crimes",
    title: "Halftone Is Not a Phase, Mom—Put These Dots Everywhere",
    dek: "How tiny ink dots faked continuous tone, conquered mass media, and escaped into your live visual stack wearing no pants and four process colors.",
    description: "Learn halftone printing history and practical Ether-MOSH Halftone settings for posters, patterns, motion graphics, projection, and print production.",
    publishedAt: "2026-08-31T08:05:00-07:00",
    readMinutes: 5,
    image: "/news/halftone-press-revolt.jpg",
    imageAlt: "A fictional historic print shop filled with cyan, magenta, yellow, and black halftone dots escaping from a screened portrait",
    imageCaption: "Management asked the dots to return to a regular screen. The magenta delegation demanded dental.",
    keywords: ["halftone effect", "halftone printing", "CMYK dots", "Ether-MOSH Halftone", "print design", "halftone tutorial"],
    tldr: "Halftoning simulates continuous tone with regularly spaced dots whose size carries tonal information. Ether-MOSH turns that print logic into an animated GPU effect; Amount blends it in and Dot Size moves from fine texture to giant graphic circles.",
    satireDisclosure: "The dot uprising and its labor demands are fictional. The print history, process explanation, MOSH controls, and production cautions are real.",
    dispatch: [
      "A fictional press foreman named Dolores Registration lost control of the cyan plate at lunch. By two o'clock magenta had unionized, yellow was inside the ventilation system, and black was carrying the composition while everybody else took credit.",
      "Traditional printing cannot lay down a smooth little fog of half-black ink on command. It prints ink or no ink. Tiny dots of changing size trick the eye into reading shades between those states.",
    ],
    explanation: [
      "The Library of Congress describes halftone photomechanical prints as reproductions distinguished by dot or line patterns created with a screen, used to reproduce continuous-tone originals such as photographs. Commercial halftone reproduction arrived in the 1880s and changed illustrated publishing.",
      "Process color separates cyan, magenta, yellow, and black screens at different angles. Ether-MOSH borrows that logic in a live three-channel shader and uses Dot Size plus Amount to move between photograph and graphic field.",
    ],
    steps: [
      "Load an image with simple lighting and recognizable midtones, then add Halftone from Color.",
      "Set Amount around 0.45 and Dot Size around 0.25 so the image remains a picture instead of becoming upholstery.",
      "Raise Dot Size for posters, projection, thumbnails, or coarse comic energy. Lower it for editorial texture and faces.",
      "Add Duotone to control the palette, or Photocopy after it for filthy repro edges.",
      "For print, export a proof and inspect it at final physical size. Your monitor is not your press and it has been lying to you since birth.",
    ],
    parameters: [
      { control: "Amount", purpose: "Blend between source and screened result", low: "Subtle print texture", high: "Dots dominate", sweetSpot: "0.40–0.78" },
      { control: "Dot Size", purpose: "Screen scale from fine to coarse", low: "Fine editorial screen", high: "Large graphic dots", sweetSpot: "Match output size" },
      { control: "Output scale", purpose: "How dots survive reproduction", low: "Fine detail may alias", high: "Coarse dots hold at distance", sweetSpot: "Proof at 100%" },
    ],
    uses: [
      { title: "Posters + packaging", body: "Use enough dot size to survive the final stock and viewing distance. A microscopic screen that vanishes in print is unpaid prepress performance art." },
      { title: "Patterns + textiles", body: "Large dots become repeat motifs; fine screens create texture. Test seams, garment scale, and separation before repeating the incident across six yards of polyester." },
      { title: "Projection + LED", body: "Coarser settings survive imperfect panels and distance. Animate Dot Size gently with bass for a breathing surface instead of a strobing eye exam." },
      { title: "Education + archives", body: "Compare a MOSH frame with a scanned newspaper under magnification: the same idea—tone encoded by marks—moves from print history into real-time graphics." },
    ],
    quote: "A halftone dot is a binary decision pretending to be nuance. Relatable, honestly.",
    quoteAttribution: "Dolores Registration, fictional foreman and real mood",
    downloadHref: "/news/downloads/halftone-field-card.md",
    product: {
      name: "Aesthetic Rebellion Word Cloud Bucket Hat",
      href: "https://aestheticrebellion.store/products/aesthetic-rebellion-word-cloud-bucket-hat",
      copy: "Aggressively visible sponsorship: aestheticrebellion.store would like to place the Aesthetic Rebellion Word Cloud Bucket Hat directly between you and financial maturity. It is reversible, because even product placement deserves two screen angles.",
    },
    sources: [
      { label: "Library of Congress — Halftone photomechanical prints", href: "https://www.loc.gov/pictures/item/tgm004832/", note: "Definition, reproduction use, and commercial-era context." },
      { label: "Adobe — Prepress terminology", href: "https://www.adobe.com/studio/print/pdf/prepress_terms.pdf", note: "Halftone screening and process-color dot arrays." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current parameters and shader source." },
    ],
    relatedEffects: ["duotone", "photocopy", "crossHatch", "moire"],
    faqs: [
      { question: "What is a halftone effect?", answer: "It represents continuous tones with discrete dots. Larger or denser dots read darker; smaller or separated dots read lighter." },
      { question: "Is MOSH Halftone a press-ready CMYK separation?", answer: "No. It is a live visual effect inspired by process-screen logic, not a replacement for professional separation, trapping, ink limits, or a physical proof." },
      { question: "What Dot Size should I use?", answer: "Use finer dots for detailed editorial texture and larger dots for posters, patterns, projections, or anything viewed at a distance." },
      { question: "Where is Halftone in Ether-MOSH?", answer: "Open the FX panel, select Color, and add Halftone. Its two controls are Amount and Dot Size." },
    ],
  },
  {
    slug: "make-moire-before-moire-makes-you-sick",
    subjectKind: "effect",
    effectId: "moire",
    effectName: "Moire",
    category: "Optical Incident",
    title: "Make Moire Before Moire Makes You Sick",
    dek: "Two innocent grids walk into a frame, disagree by four percent, and produce a giant beat pattern that now owns the venue.",
    description: "Understand moire interference and learn practical Ether-MOSH Moire settings for op art, projection mapping, live visuals, print proofs, patterns, and education.",
    publishedAt: "2026-08-31T08:10:00-07:00",
    readMinutes: 5,
    image: "/news/moire-optical-hearing.jpg",
    imageAlt: "A fictional optical hearing where overlapping fine line grids create a large moire wave behind a tribunal",
    imageCaption: "The tribunal ruled that the grids were individually harmless and collectively a pain in the ass.",
    keywords: ["moire effect", "moire pattern", "optical interference", "Ether-MOSH Moire", "op art", "projection mapping effects"],
    tldr: "Moire is a large interference pattern created when similar repeating grids overlap with a slight change in angle, spacing, or scale. Ether-MOSH animates two near-matching grids; Amount controls visibility and Pitch controls frequency.",
    satireDisclosure: "The Department of Optical Incidents and tribunal are fictional. The interference physics, cultural references, accessibility note, and MOSH workflow are real.",
    dispatch: [
      "The Department of Optical Incidents convened an emergency hearing after two grids were seen overlapping without a permit. Each looked boring alone. Together they generated a rolling wave large enough to swallow the municipal logo.",
      "Expert witness Dr. Patty Repeat—fabricated, overqualified, and furious—explained that nobody added the big wave. It emerged from the small mismatch between the patterns. The room requested a recess. The pattern requested a higher Pitch setting.",
    ],
    explanation: [
      "Moire appears when similar periodic structures overlap with a slight difference in angle, spacing, or scale. Their alignments create a larger beat pattern. It can be a camera or print artifact, a measurement tool, a material-science phenomenon, or the entire damn artwork.",
      "MoMA discusses optical interference in Liz Deschenes's Moire #25, while NIST describes moire in stacked atomic layers. Ether-MOSH recreates the mechanism with two fine grids: one rotates and runs at a slightly different frequency, producing a moving coarse field.",
    ],
    steps: [
      "Load a high-contrast image with broad shapes. Fine striped fabric may summon a second, less cooperative moire.",
      "Add Moire from Geometry. Begin with Amount around 0.25 and Pitch around 0.35.",
      "Increase Pitch until the grids resolve at your actual output size. Do not judge a venue loop in a postage-stamp preview like a tiny coward.",
      "Raise Amount until the pattern supports the source. Add Duotone for control or Bloom for luminous projection.",
      "Test on the real display, projector, camera, and print process. Resampling can create interference your laptop never showed you.",
    ],
    parameters: [
      { control: "Amount", purpose: "Visibility of the interference treatment", low: "Quiet shimmer", high: "Pattern dominates", sweetSpot: "0.18–0.62" },
      { control: "Pitch", purpose: "Frequency of the two source grids", low: "Broad calm structure", high: "Dense volatile field", sweetSpot: "Output-dependent" },
      { control: "Scale + camera", purpose: "Adds sensor and resampling interactions", low: "Stable in one context", high: "Secondary moire", sweetSpot: "Test final hardware" },
    ],
    uses: [
      { title: "Live installation", body: "Project onto simple surfaces first, then introduce architecture. Slow Pitch changes make a static wall feel volumetric without requiring a headset waiver." },
      { title: "Print + pattern", body: "Use moire intentionally only after physical proofing. The press, paper, screen ruling, scanner, and social thumbnail may each generate their own opinion." },
      { title: "Motion + performance", body: "Map Amount conservatively to audio and let Pitch drift. Rapid high-contrast changes can be uncomfortable, so keep an accessible low-intensity state." },
      { title: "Museum + education", body: "Layer two printed transparencies and rotate one by hand, then compare the analog beat pattern with Ether-MOSH. The principle becomes obvious without a paragraph wearing a lab coat." },
    ],
    quote: "Moire is what happens when repetition develops a disagreement and makes it everybody's problem.",
    quoteAttribution: "Dr. Patty Repeat, not a real doctor or person",
    downloadHref: "/news/downloads/moire-field-card.md",
    product: {
      name: "Chromatic Sweep Reversible Bucket Hat",
      href: "https://aestheticrebellion.store/products/chromatic-sweep-reversible-bucket-hat",
      copy: "Here comes the shameless sponsorship beam: the Chromatic Sweep Reversible Bucket Hat from aestheticrebellion.store contains enough competing color movement to make a moire grid file a restraining order. Please admire the nerve of inserting a hat into optical science.",
    },
    sources: [
      { label: "MoMA — Surface and Light: Liz Deschenes", href: "https://www.moma.org/explore/inside_out/2012/07/12/surface-and-light-liz-deschenes/", note: "Moiré as interference, misregistration, and photographic artwork." },
      { label: "NIST — Moiré Patterns Open Up More Possibilities", href: "https://www.nist.gov/news-events/news/2019/02/moire-patterns-open-more-possibilities-quantum-information", note: "Interference from overlaid periodic structures in material science." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current parameters and shader source." },
    ],
    relatedEffects: ["halftone", "duotone", "bloom", "feedbackTunnel"],
    faqs: [
      { question: "What causes a moire pattern?", answer: "Two similar repeating patterns overlap with a small difference in angle, spacing, or scale. Their periodic alignments form a larger visible beat pattern." },
      { question: "Is moire always a mistake?", answer: "No. It can be an unwanted artifact, but artists, designers, scientists, and engineers also use it intentionally." },
      { question: "Can I print MOSH Moire artwork?", answer: "Yes, but proof it physically. Scaling, screen ruling, paper, camera sensors, and later resampling can introduce additional interference." },
      { question: "Where is Moire in Ether-MOSH?", answer: "Open the FX panel, select Geometry, and add Moire. Start at low Amount and adjust Pitch at final output size." },
    ],
  },
  {
    slug: "break-the-keyframes-before-lunch",
    subjectKind: "effect",
    effectId: "datamosh",
    effectName: "Datamosh",
    category: "Codec Misconduct",
    title: "Break the Keyframes Before Lunch",
    dek: "Your video is too stable, the group chat prefers the broken cut, and compression has finally become a creative collaborator instead of a tiny bureaucrat in your export window.",
    description: "Learn how datamoshing uses video-compression logic and how to control Ether-MOSH Datamosh for loops, live visuals, music videos, projections, and print stills.",
    publishedAt: "2026-09-01T08:00:00-07:00",
    readMinutes: 5,
    image: "/news/datamosh-keyframe-intervention.jpg",
    imageAlt: "Friends in an apartment react to a birthday video breaking into bright datamosh blocks on a monitor",
    imageCaption: "The birthday edit broke at 1:17 a.m. Nobody fixed it because, for once, the group chat had excellent notes.",
    keywords: ["datamosh effect", "how to datamosh", "video compression glitch", "Ether-MOSH Datamosh", "motion vectors", "glitch video"],
    tldr: "Classic datamoshing exploits dependencies between compressed video frames so motion data affects the wrong picture. Ether-MOSH makes a live visual interpretation: Amount decides how many blocks move and how far, while Block Size controls the chunks.",
    satireDisclosure: "The apartment emergency is fictional. The compression concepts, MOSH controls, and production advice are real.",
    dispatch: [
      "You are making a birthday edit for a friend. The clean version is sincere, competent, and dead behind the eyes. Then playback hiccups, a face drags through the kitchen wall, and five people immediately yell, ‘Keep that.’ This is how an accident gets promoted above you.",
      "Datamoshing became beloved because compressed video already contains weird relationships between complete images, predicted changes, and motion. Break the relationship on purpose and movement starts borrowing the wrong body. It is technically rude and visually generous.",
    ],
    explanation: [
      "Many video codecs use full image frames alongside predicted frames that store changes relative to other frames. Classic datamoshing removes, rearranges, or misuses those reference points so motion information carries old imagery into new movement.",
      "Ether-MOSH does not corrupt an encoded file. Its real-time shader divides the picture into blocks, chooses changing regions, and offsets them as Amount rises. The result speaks the same block-reuse dialect while staying responsive enough to perform live.",
    ],
    steps: [
      "Load a clip with obvious movement: dancing, camera pans, hands, traffic, or somebody entering frame with unnecessary confidence.",
      "Open Data Corruption and add Datamosh. Start Amount near 0.35 and Block Size near 0.025.",
      "Raise Amount until motion begins stealing chunks of the frame. Stop before every subject becomes the same rectangular weather event.",
      "Increase Block Size for chunky poster-like damage; lower it when faces and gestures still need to read.",
      "Record a short loop through a strong movement change. For print, export the one frame where the smear has structure instead of merely evidence.",
    ],
    parameters: [
      { control: "Amount", purpose: "How many blocks move and how far", low: "Occasional slips", high: "Near-total block migration", sweetSpot: "0.30–0.68" },
      { control: "Block Size", purpose: "Scale of reused image chunks", low: "Fine digital chatter", high: "Large graphic slabs", sweetSpot: "0.015–0.040" },
      { control: "Source motion", purpose: "Gives displacement a readable event", low: "Texture more than action", high: "Clear trails and handoffs", sweetSpot: "One bold movement" },
    ],
    uses: [
      { title: "Music video + social", body: "Cut a clean performance into brief mosh handoffs. Two strong failures feel authored; forty seconds of soup feels like the laptop won." },
      { title: "Projection + VJ", body: "Use broad movement and medium blocks so the damage survives distance. Trigger Amount on transitions instead of stapling it to every kick." },
      { title: "Print + cover art", body: "Capture a frame where a block edge reinforces the composition, then use the print-ready export. Compression history is allowed on paper." },
      { title: "Teaching compression", body: "Compare a literal encoded-file datamosh with the MOSH shader. One alters codec dependencies; the other performs their visual behavior in real time." },
    ],
    quote: "The clean cut explained the party. The broken cut remembered what it felt like.",
    quoteAttribution: "A friend who accidentally gave the correct edit note",
    downloadHref: "/news/downloads/datamosh-field-card.md",
    product: {
      name: "Liquid Glitch Snapback",
      href: "https://aestheticrebellion.store/products/liquid-glitch-snapback",
      copy: "aestheticrebellion.store has inserted the Liquid Glitch Snapback here because your motion vectors needed a hat. It cannot repair a codec. It can make you look suspiciously calm while the footage dissolves.",
    },
    sources: [
      { label: "Adobe Media Encoder reference", href: "https://helpx.adobe.com/en/pdf/cs6/mediaencoder_reference.pdf", note: "Reference definitions for I, P, and B frames and keyframe intervals." },
      { label: "FFmpeg codec documentation", href: "https://www.ffmpeg.org/ffmpeg-codecs.html", note: "Technical reference for keyframes, reference frames, and motion-vector controls." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current Datamosh controls and shader implementation." },
    ],
    relatedEffects: ["blockShift", "compressionTears", "rgbShift", "filmGrain"],
    faqs: [
      { question: "Is Ether-MOSH literally corrupting my video file?", answer: "No. It performs a responsive GPU interpretation of datamosh block reuse; your source file remains intact." },
      { question: "What footage works best?", answer: "Clips with clear motion, cuts, pans, gestures, or subjects crossing the frame make displaced blocks easier to read." },
      { question: "What does Block Size change?", answer: "It changes the scale of the sampled chunks, from fine digital chatter to large graphic blocks." },
      { question: "Where is Datamosh?", answer: "Open the FX panel, choose Data Corruption, and add Datamosh. Its live controls are Amount and Block Size." },
    ],
  },
  {
    slug: "your-fake-crt-looks-cheap",
    subjectKind: "effect",
    effectId: "crtPhosphor",
    effectName: "CRT",
    category: "Retro Intervention",
    title: "Your Fake CRT Looks Cheap—Stop at the Scanlines",
    dek: "A tube display is curved glass, phosphors, masks, bloom, and decades of accumulated emotional baggage. Three gray lines over a clean render are not fooling anybody.",
    description: "Learn how CRT displays form images and how to use Ether-MOSH CRT Curvature, Shadow Mask, and Bloom for live visuals, motion design, installations, and print.",
    publishedAt: "2026-09-01T08:05:00-07:00",
    readMinutes: 5,
    image: "/news/crt-scanline-intervention.jpg",
    imageAlt: "A tired VJ sits beside a glowing curved CRT while a creative director holds a retro moodboard",
    imageCaption: "The brief said ‘retro.’ The television arrived with actual structure and immediately became difficult to manage.",
    keywords: ["CRT effect", "CRT phosphor", "shadow mask", "Ether-MOSH CRT", "retro video effect", "scanline effect"],
    tldr: "A CRT scans an electron beam across phosphors behind curved glass, with a shadow mask or grille helping steer color. Ether-MOSH models the look with Curvature, Shadow Mask, and Bloom—not a lonely scanline overlay wearing nostalgia as a fake mustache.",
    satireDisclosure: "The creative director and workplace tension are fictional. The display principles, controls, and production cautions are real.",
    dispatch: [
      "A creative director leans over your shoulder and says, ‘Can you make it more old TV?’ You add scanlines. They nod for seven seconds, then ask why it still looks like a new video wearing blinds. This is annoying because they are right.",
      "A real cathode-ray tube is a physical imaging system: beam, phosphors, glass geometry, color structure, glow, and imperfect edges. The look came from hardware doing its job, not an opacity layer named FINAL_crt_07.",
    ],
    explanation: [
      "Inside a color CRT, electron guns aim beams toward red, green, and blue phosphors. A shadow mask or aperture grille helps each beam reach the intended color structure, while the scan and phosphor response build the visible image across the tube.",
      "Ether-MOSH bends the source as if it sits on curved glass, overlays a fine RGB phosphor structure, and adds controlled glow. Curvature establishes the object; Shadow Mask establishes the surface; Bloom lets bright areas bleed without turning the frame into a scented candle.",
    ],
    steps: [
      "Load footage with bright edges, faces, typography, game graphics, or a dark background that gives glow somewhere to exist.",
      "Add CRT from Atmosphere. Start Curvature at 0.30, Shadow Mask at 0.45, and Bloom at 0.25.",
      "Set Curvature first. If the picture looks trapped in a novelty fisheye, lower it and apologize to the corners.",
      "Raise Shadow Mask while viewing at final display size. Too fine can alias; too strong can chew through detail.",
      "Add Bloom last, then test the actual projector, LED wall, phone, or export. Different resampling produces different tiny lies.",
    ],
    parameters: [
      { control: "Curvature", purpose: "Bends the image toward tube geometry", low: "Mostly flat panel", high: "Pronounced barrel shape", sweetSpot: "0.20–0.48" },
      { control: "Shadow Mask", purpose: "Strength of the RGB phosphor structure", low: "Soft texture", high: "Visible color grille", sweetSpot: "0.35–0.65" },
      { control: "Bloom", purpose: "Bleed around bright phosphors", low: "Crisp and dry", high: "Soft luminous spill", sweetSpot: "0.18–0.45" },
    ],
    uses: [
      { title: "Venue visuals", body: "CRT can make pristine playback feel physical. Keep the mask broad enough to survive the LED processor instead of fighting a pixel grid with another pixel grid." },
      { title: "Games + motion graphics", body: "Use Curvature and Bloom to frame menus or simulated broadcasts, then reserve stronger masks for close-ups and transitions." },
      { title: "Print + editorial", body: "Export a still with readable phosphor structure and proof it at size. Fine stripes can become accidental moire when reduced." },
      { title: "Exhibition + archive", body: "Pair the effect with photographs of real CRT subpixels to discuss how display hardware becomes an aesthetic after the hardware disappears." },
    ],
    quote: "Scanlines are a symptom. The tube is the whole strange little body.",
    quoteAttribution: "The venue tech who has carried enough televisions",
    downloadHref: "/news/downloads/crt-field-card.md",
    product: {
      name: "Channel Static Hoodie",
      href: "https://aestheticrebellion.store/products/channel-static-hoodie",
      copy: "This lesson is interrupted by the Channel Static Hoodie at aestheticrebellion.store, a garment scientifically unable to make your scanlines more authentic but extremely willing to stand near a television and take credit.",
    },
    sources: [
      { label: "iFixit — CRT Displays", href: "https://www.ifixit.com/Wiki/CRT_Displays", note: "Overview of electron guns, phosphors, shadow masks, aperture grilles, and raster scanning." },
      { label: "Sarnoff Collection — First Shadow Mask CRT", href: "https://embark.tcnj.edu/objects-1/info/126?objectName=First+Shadow+Mask+Cathode+Ray+Tube+%28CRT%29&sort=0", note: "Museum object record for early color shadow-mask tube development." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current CRT parameters and shader source." },
    ],
    relatedEffects: ["vhsBleed", "filmGrain", "chromaAberrate", "vignette"],
    faqs: [
      { question: "Is a CRT look just scanlines?", answer: "No. Tube curvature, phosphor color structure, mask or grille behavior, glow, and edge response are all part of the display's visual character." },
      { question: "Why does the mask shimmer after export?", answer: "Fine repeated stripes can alias during scaling or compression. Judge them at final size and reduce Shadow Mask when needed." },
      { question: "Can CRT work in print?", answer: "Yes, but proof the physical output because phosphor stripes can merge or form unintended moire after resampling." },
      { question: "Where is CRT?", answer: "Open the FX panel, choose Atmosphere, and add CRT. Its controls are Curvature, Shadow Mask, and Bloom." },
    ],
  },
  {
    slug: "forge-mode-already-started-the-fight",
    subjectKind: "mode",
    effectName: "Forge Mode",
    category: "Mode Manual",
    title: "Forge Mode Already Started the Fight",
    dek: "Stop choosing every pixel like a middle manager. Give the generator a direction, let six visual systems argue, and intervene when the argument gets good.",
    description: "Learn how Ether-MOSH Forge Mode combines six seeded procedural generators, effect stacks, crossfades, audio response, seamless controls, and print-ready exports.",
    publishedAt: "2026-09-01T08:10:00-07:00",
    readMinutes: 5,
    image: "/news/forge-mode-six-generators.jpg",
    imageAlt: "An artist smiles at a workstation surrounded by six distinct procedural visual worlds",
    imageCaption: "The machine made six suggestions. For once, none of them began with ‘make the logo bigger.’",
    keywords: ["Ether-MOSH Forge Mode", "generative art tool", "procedural visuals", "reaction diffusion art", "VJ generator", "print ready generative art"],
    tldr: "Forge Mode is Ether-MOSH's seeded procedural source. It rotates through six generators, composes effect stacks, crossfades between states, reacts to audio, accepts optional image material, and can output seamless or print-ready art without requiring a source clip.",
    satireDisclosure: "No generator achieved sentience or filed a complaint. The six systems, mode behavior, controls, and export details are real.",
    dispatch: [
      "You open MOSH with no footage and the mild panic of a person who promised visuals before finding visuals. Forge does not ask for a moodboard. It starts growing blobs, fields, cracks, contours, and chemical-looking organisms while you decide which accident deserves custody.",
      "That is the useful division of labor: the system proposes, you judge. A seed keeps a direction reproducible, transitions keep changes from arriving like a folding chair, and the normal MOSH stack remains available when a generator needs tasteful damage.",
    ],
    explanation: [
      "Forge includes Volumetric Bloom, Drift Field, Shatter Field, Pour Bloom, Contour Bands, and a stateful Gray-Scott Reaction Diffusion simulation. Each generator has its own structure, then a shared finishing pass and MOSH effect stack give the family a related visual language.",
      "Shuffle can change the generator and stack while a 2.4-second crossfade carries the previous state into the next. Seeds, palette direction, intensity, audio response, optional base imagery, mosaic density, overlay, kaleidoscope, and seamless constraints let you guide the system without drawing every cell by hand.",
    ],
    steps: [
      "Open the source selector and choose the Flame icon labeled Forge. No upload is required.",
      "Shuffle until the generator family suits the job, then set Intensity before decorating the stack into witness protection.",
      "Turn on audio response for performance, or leave it off when you need a stable print composition.",
      "Add a base image and mosaic overlay when the abstract field needs memory of a photograph. Enable Seamless before composing a repeat.",
      "Export a loop, still, seamless tile, or a 2048–8000 px print-ready PNG stamped at your selected DPI.",
    ],
    parameters: [
      { control: "Generator + seed", purpose: "Chooses a visual system and repeatable state", low: "One held direction", high: "Frequent evolution", sweetSpot: "Hold after a strong draw" },
      { control: "Intensity", purpose: "Pushes generator and effect-stack behavior", low: "Sparse and legible", high: "Dense and unruly", sweetSpot: "0.42–0.72" },
      { control: "Seamless + overlay", purpose: "Prepares repeats or mixes source material", low: "Pure procedural source", high: "Image-led construction", sweetSpot: "Job-dependent" },
    ],
    uses: [
      { title: "Live visuals", body: "Let generator changes crossfade instead of hard-cutting every bar. Audio response is a collaborator, not a court order to wiggle everything." },
      { title: "Album + campaign systems", body: "Reuse one seed and palette across covers, clips, and social crops so the family feels related without becoming identical triplets." },
      { title: "Print + textile", body: "Freeze a strong state, enable seamless constraints for repeats, and export at the final pixel target. Proof before manufacturing a very expensive argument." },
      { title: "Education + installation", body: "Compare field, cellular, contour, metaball, and reaction-diffusion systems to show how different algorithms produce different kinds of organic structure." },
    ],
    quote: "Generative art is not pressing a button. It is knowing which result earned the right to stay.",
    quoteAttribution: "The operator, still employed for judgment",
    downloadHref: "/news/downloads/forge-mode-field-card.md",
    product: {
      name: "Prism Facet Mosaic V-Neck Top",
      href: "https://aestheticrebellion.store/products/prism-facet-mosaic-v-neck-top",
      copy: "Forge would like to disclose a shameless internal sponsorship by the Prism Facet Mosaic V-Neck Top at aestheticrebellion.store. It is what happens when a procedural field gets payroll, fabric, and absolutely no request to calm down.",
    },
    sources: [
      { label: "V&A — Digital Art", href: "https://www.vam.ac.uk/articles/digital-art", note: "Historical context for computer-generated, algorithmic, and interactive artwork." },
      { label: "Ether-MOSH effects library", href: "/effects", note: "The effects Forge can compose over its procedural source." },
      { label: "Open Forge Mode", href: "/edit", note: "Current generators, controls, transitions, and export workflow." },
    ],
    relatedEffects: ["bloom", "liquidWarp", "kaleidoscope", "filmGrain"],
    faqs: [
      { question: "Does Forge Mode need a photo or video?", answer: "No. It can generate a complete procedural source by itself, with optional imagery when you want to mix in recognizable material." },
      { question: "How many generators are in Forge?", answer: "Six: Volumetric Bloom, Drift Field, Shatter Field, Pour Bloom, Contour Bands, and Reaction Diffusion." },
      { question: "Can Forge make seamless patterns?", answer: "Yes. Enable Seamless before generating and inspect a repeat proof before production." },
      { question: "Can I reproduce a result?", answer: "The seed preserves the underlying direction; keep it and your settings when you need a related version later." },
    ],
  },
  {
    slug: "stop-gaslighting-the-seam",
    subjectKind: "mode",
    effectName: "Pattern / Motif Mode",
    category: "Mode Manual",
    title: "Your Pattern Doesn't Tile—Stop Gaslighting the Seam",
    dek: "That vertical scar is not ‘organic variation.’ Pattern mode lives under Motif, and it has a repeat proof specifically so the seam can be confronted before it reaches upholstery.",
    description: "Learn how Ether-MOSH Pattern mode, labeled Motif and Motif Maestro, builds seamless tiles and repeat proofs from Forge, uploaded images, or camera stills.",
    publishedAt: "2026-09-01T08:15:00-07:00",
    readMinutes: 5,
    image: "/news/pattern-mode-seam-hearing.jpg",
    imageAlt: "A textile designer points at a seam in a bold mirrored repeating pattern across fabric and wallpaper",
    imageCaption: "The seam claimed it was part of the concept. The three-by-three repeat proof produced receipts.",
    keywords: ["Ether-MOSH pattern mode", "Motif Maestro", "seamless pattern generator", "repeat tile", "textile pattern design", "seamless PNG"],
    tldr: "Pattern mode appears as Motif in the source selector. Motif Maestro can use Forge, an upload, or a camera still; forces seamless mirror tiling by default; controls direction, symmetry, density, and variation; and exports either a 2048 px tile or a 3×3 repeat proof with print DPI metadata.",
    satireDisclosure: "The seam hearing is fictional. The Motif controls, repeat workflow, export behavior, and production cautions are real.",
    dispatch: [
      "You make a beautiful tile. You duplicate it once. A hard vertical seam appears with the confidence of a landlord asking for another deposit. You zoom in, call it texture, zoom out, and discover texture has formed a fence.",
      "Pattern mode exists because a single attractive square is not yet a pattern. Repetition creates new shapes, new spacing, and new failures. Motif Maestro makes those relationships visible before your printer makes them expensive.",
    ],
    explanation: [
      "In the current interface, Pattern mode is labeled Motif and opens the Motif Maestro workspace. It accepts a Forge source, uploaded image, or camera still, then builds directional repeats using mirror, rotate, or kaleidoscope symmetry with adjustable density and variation.",
      "The workspace starts with Seamless and mirror tiling enabled, generates a 2048 px motif tile, and can assemble a 3×3 repeat proof. The readout scores seamlessness, composition, contrast, and motif strength so you can inspect the system—not just admire one square in isolation.",
    ],
    steps: [
      "Choose the Sparkles source labeled Motif. If you were looking for a button named Pattern, congratulations: this sentence saved a search party.",
      "Choose Forge, Upload, or Camera as the source, then pick all-direction, horizontal, or vertical movement.",
      "Set symmetry to mirror, rotate, or kaleidoscope. Adjust Density for spacing and Variation for how far the arrangement evolves.",
      "Generate, inspect the readout, then view the 3×3 proof. Look at every edge and the larger accidental shapes formed by repetition.",
      "Export the 2048 px tile or repeat proof with your selected print DPI, then test it at the real product scale.",
    ],
    parameters: [
      { control: "Direction", purpose: "Organizes motif flow across the repeat", low: "Single-axis order", high: "All-direction movement", sweetSpot: "Match the product shape" },
      { control: "Symmetry", purpose: "Mirror, rotate, or kaleidoscope tiling", low: "Readable repetition", high: "Dense radial structure", sweetSpot: "Mirror first" },
      { control: "Density + variation", purpose: "Controls spacing and evolutionary distance", low: "Airy and consistent", high: "Crowded and surprising", sweetSpot: "Proof at final scale" },
    ],
    uses: [
      { title: "Fabric + apparel", body: "Use the repeat proof to catch seams, scale problems, and accidental focal points before one weird flower lands on every left armpit." },
      { title: "Wallpaper + interiors", body: "Judge the larger rhythm across several tiles. A repeat that looks balanced on a laptop can become a marching column across a wall." },
      { title: "Packaging + identity", body: "Hold the seed, symmetry, and palette to create a recognizable system across boxes, tissue, labels, and campaign backgrounds." },
      { title: "Education + sampling", body: "Compare mirror, rotate, and kaleidoscope proofs from the same source to show how repeat logic changes composition without changing the motif itself." },
    ],
    quote: "A seamless tile hides the join. A good pattern makes you stop looking for it.",
    quoteAttribution: "The repeat proof, finally allowed to testify",
    downloadHref: "/news/downloads/pattern-mode-field-card.md",
    product: {
      name: "Seamless Patterns SVG Bundle — 800+ Cut Files",
      href: "https://aestheticrebellion.store/products/seamless-patterns-svg-bundle-800-cut-files",
      copy: "Subtlety has left the building: aestheticrebellion.store sells a Seamless Patterns SVG Bundle with more than 800 cut files, placed here directly in front of your face because even satire understands inventory alignment.",
    },
    sources: [
      { label: "Adobe Illustrator — Create a pattern", href: "https://www.adobe.com/learn/illustrator/web/create-pattern", note: "Practical reference for repeat tiles, spacing, scale, brick, and half-drop structures." },
      { label: "Adobe Illustrator — Repeat patterns overview", href: "https://helpx.adobe.com/in/illustrator/desktop/paint-and-fill/create-and-edit-patterns/repeat-patterns-overview.html", note: "Reference for grid, radial, and mirror repeat systems." },
      { label: "Open Motif Maestro", href: "/edit", note: "Current source, direction, symmetry, density, variation, proof, and export controls." },
    ],
    relatedEffects: ["kaleidoscope", "mirrorKaleido", "moire", "halftone"],
    faqs: [
      { question: "Where is Pattern mode in Ether-MOSH?", answer: "It is labeled Motif in the source selector. Choose the Sparkles icon to open Motif Maestro." },
      { question: "What can I use as a pattern source?", answer: "Forge output, an uploaded still image, or a camera still." },
      { question: "What is a repeat proof?", answer: "It places the tile in a larger grid so seams, spacing, and accidental shapes become visible before production." },
      { question: "What does Motif export?", answer: "A 2048 px seamless tile or a 3×3 repeat proof PNG with the selected print DPI metadata." },
    ],
  },
  {
    slug: "turn-the-kaleidoscope-effect-until-it-confesses",
    subjectKind: "effect",
    effectId: "kaleidoscope",
    effectName: "Kaleidoscope",
    category: "Optical Misconduct",
    title: "Turn the Kaleidoscope Effect Until the Room Confesses",
    dek: "Two controls, one folding chair, and enough radial symmetry to make a venue inspector question whether furniture has achieved collective consciousness.",
    description: "Learn how the kaleidoscope effect uses mirrored radial symmetry and how to set Ether-MOSH Segments and Spin for patterns, motion, projection, print, and education.",
    publishedAt: "2026-09-01T09:15:00-07:00",
    readMinutes: 5,
    image: "/news/kaleidoscope-venue-inspection.jpg",
    imageAlt: "A fictional venue inspector beside a folding chair as the chair repeats into a static acid-green, magenta, and cyan kaleidoscope projection",
    imageCaption: "The chair passed inspection. Its sixteen reflected cousins are waiting on separate paperwork.",
    keywords: ["kaleidoscope effect", "Ether-MOSH Kaleidoscope", "radial mirror effect", "kaleidoscope tutorial", "projection visuals", "seamless pattern design", "accessible motion graphics"],
    tldr: "The kaleidoscope effect turns one image into rotating radial mirror symmetry. Ether-MOSH converts the frame to polar space, divides it with Segments, folds each wedge, then samples the source; Spin rotates the fold over time. Start at 6 Segments and 0.15 Spin. Use 0 Spin for a static or lower-motion result.",
    satireDisclosure: "The venue inspection, inspector Mara Wedge, and multiplying-chair incident are fictional. The optical history, Ether-MOSH controls, shader behavior, accessibility guidance, and production advice are factual and sourced.",
    dispatch: [
      "At 09:15, fictional venue inspector Mara Wedge entered Studio B and found one folding chair reflected into a radial committee of sixteen. The committee had no permit, no fire marshal, and one aggressively centered vanishing point.",
      "Wedge asked the projection operator to stop the rotation. The operator set Spin to zero, the chair caucus froze, and everybody discovered that a kaleidoscope can be dramatic without moving like it owes the room money.",
    ],
    explanation: [
      "David Brewster's 1817 British patent 4136 describes a new optical instrument called the kaleidoscope for creating forms and patterns useful to the ornamental arts. A National Museums Scotland instrument from about 1820 uses reflection to create multiple images and identifies Brewster as its designer; a University of St Andrews museum record documents another Brewster patent kaleidoscope dated 1816–1830.",
      "Ether-MOSH recreates the visual logic rather than simulating physical glass. Its shader converts each pixel position to an angle and radius, divides the circle by Segments, mirrors every angular wedge, and samples the source at the folded coordinate. Spin adds a continuous angular offset; at 0, the fold stays still.",
      "Kaleidoscope does not generate flashes by itself, but fast rotation, high contrast, and flashing effects elsewhere in a stack can still be uncomfortable. Keep public-facing motion slow, provide a static option when practical, and test any flashing output against WCAG's three-flashes-or-below-threshold guidance.",
    ],
    steps: [
      "Load an asymmetrical image or clip with one strong off-center subject, then open the FX panel and add Kaleidoscope from Geometry.",
      "Set Segments to 6 and Spin to 0.15. Six wedges keep the source recognizable while the slow turn makes the fold easy to read.",
      "Try 2–4 Segments for bold reflected architecture, or 8–12 for a denser mandala. The available range is 2–16; more is not automatically more employed.",
      "Set Spin to 0 for print, a held installation state, or a lower-motion version. For venues, keep motion deliberate and avoid stacking rapid flashes or hard luminance cuts.",
      "Export a still or short loop. For fabric or wallpaper, use the still as a Motif source and inspect the 3×3 repeat proof before manufacturing a radial seam emergency.",
    ],
    parameters: [
      { control: "Segments", purpose: "Divides the circle into mirrored angular wedges", low: "2–4 bold reflections", high: "12–16 dense symmetry", sweetSpot: "6" },
      { control: "Spin", purpose: "Rotates the folded sampling angle over time", low: "0 static; 0.05 gentle", high: "1 fast rotation", sweetSpot: "0.15" },
      { control: "Source framing", purpose: "Determines what each wedge repeats", low: "Centered source feels regular", high: "Off-center detail creates movement", sweetSpot: "One clear asymmetry" },
    ],
    uses: [
      { title: "Print + pattern", body: "Freeze Spin, export a strong still, then bring it into Motif Maestro for a repeat proof. Check the center, corners, and product scale before the mandala colonizes a duvet." },
      { title: "Vector + Lottie", body: "Trace a few dominant wedge boundaries instead of every raster detail, or use a short low-Spin loop as a masked motion layer. Simpler symmetry survives small screens and lightweight animation." },
      { title: "Projection + venue", body: "Use architecture, dancers, props, or logos with a readable silhouette. Keep rotation slow, rehearse at full screen brightness, and offer a static cue for motion-sensitive audiences." },
      { title: "Museum + education", body: "Place a physical two-mirror kaleidoscope beside the shader output to compare reflected light with coordinate folding. The pictures rhyme; the machinery does not." },
    ],
    quote: "Radial symmetry is what happens when one image gets a committee and every member insists on facing the center.",
    quoteAttribution: "Mara Wedge, fictional inspector of repeat offenses",
    downloadHref: "/news/downloads/kaleidoscope-field-card.md",
    product: {
      name: "Radial Kaleidoscope Aloha Shirt",
      href: "https://aestheticrebellion.store/products/radial-kaleidoscope-aloha-shirt",
      copy: "This science lesson is now being mugged by commerce: the Radial Kaleidoscope Aloha Shirt at aestheticrebellion.store puts green, purple, and rainbow radial tile bursts on a camp-collar shirt. Buying it will not improve Segments. It may, however, make your torso look peer-reviewed by a disco ball.",
    },
    sources: [
      { label: "University of St Andrews — Telescopic kaleidoscope", href: "https://collections.st-andrews.ac.uk/item/telescopic-kaleidoscope/1000356", note: "Museum record for a Brewster patent kaleidoscope dated 1816–1830." },
      { label: "National Museums Scotland — Telescopic kaleidoscope", href: "https://www.nms.ac.uk/collections/search/object?creator=Brewster%2C+David%2C+Sir%2C+1781+-+1868&entry=222186&page=1&view=cards", note: "Museum record for a reflection-based instrument designed by Brewster around 1820." },
      { label: "David Brewster — 1817 patent specification", href: "https://brewstersociety.com/pdf/brewster_patent.pdf", note: "Primary patent text describing the optical instrument and ornamental patterns." },
      { label: "W3C — Three Flashes or Below Threshold", href: "https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold", note: "Current accessibility guidance for evaluating flashing content." },
      { label: "Ether-MOSH Kaleidoscope registry entry", href: "/effects#kaleidoscope", note: "Current Geometry category, Segments and Spin ranges, defaults, and GLSL source." },
      { label: "Pattern Mode field report", href: "/news/stop-gaslighting-the-seam", note: "Internal guide for turning a Kaleidoscope still into a proofed repeat." },
      { label: "Moire field report", href: "/news/make-moire-before-moire-makes-you-sick", note: "Related optical-pattern guide with projection and accessibility cautions." },
    ],
    relatedEffects: ["mirror", "polarFold", "moire", "twirl"],
    faqs: [
      { question: "What does the kaleidoscope effect do?", answer: "It folds an image into mirrored radial wedges around the center, creating repeated symmetry from one source frame." },
      { question: "Where is Kaleidoscope in Ether-MOSH?", answer: "Open the FX panel, choose Geometry, and add Kaleidoscope. Its controls are Segments from 2–16 and Spin from 0–1." },
      { question: "What is a good Kaleidoscope Segments setting?", answer: "Start at 6. Use 2–4 for large readable reflections and 8–12 for a denser mandala, then judge at the final output size." },
      { question: "How do I use a kaleidoscope effect safely in projection?", answer: "Keep Spin slow, avoid rapid flashes and hard high-contrast cuts elsewhere in the stack, rehearse at full brightness, and provide a static version when practical." },
    ],
  },
];

export const NEWS_ARTICLES_BY_SLUG = new Map(NEWS_ARTICLES.map((article) => [article.slug, article]));
export const latestNewsArticles = [...NEWS_ARTICLES].sort((a, b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt));
export const newsArticlePath = (article: NewsArticle) => `/news/${article.slug}`;
