export type NewsArticle = {
  slug: string;
  subjectKind: "effect" | "mode";
  effectId?: string;
  effectName: string;
  category: string;
  title: string;
  dek: string;
  description: string;
  publishedAt: string;
  readMinutes: number;
  image: string;
  imageAlt: string;
  imageCaption: string;
  keywords: string[];
  tldr: string;
  satireDisclosure: string;
  dispatch: string[];
  explanation: string[];
  steps: string[];
  parameters: { control: string; purpose: string; low: string; high: string; sweetSpot: string }[];
  uses: { title: string; body: string }[];
  quote: string;
  quoteAttribution: string;
  downloadHref: string;
  product: { name: string; href: string; copy: string };
  sources: { label: string; href: string; note: string }[];
  relatedEffects: string[];
  faqs: { question: string; answer: string }[];
};

export type NewsLookExample = {
  scene: string;
  settings: string;
  result: string;
};

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    slug: "sort-your-pixels-before-they-sort-you",
    subjectKind: "effect",
    effectId: "pixelSort",
    effectName: "Pixel Sort",
    category: "Effect School",
    title: "Sort Your Pixels Before They Sort You",
    dek: "A practical field guide to brightness-driven smearing, why the internet fell for it, and how to weaponize it without making visual oatmeal.",
    description: "Learn what pixel sorting is, where the glitch-art technique came from, and how to use Ether-MOSH Pixel Sort for video, print, projection, patterns, and motion graphics.",
    publishedAt: "2026-08-31T08:00:00-07:00",
    readMinutes: 6,
    image: "/news/pixel-sort-bureaucracy.jpg",
    imageAlt: "Fictional workers sorting black, white, and magenta pixels beneath a portrait stretched into horizontal pixel-sort streaks",
    imageCaption: "The Department of Pixel Labor denies that brightness has become a caste system. The pixels have retained counsel.",
    keywords: ["pixel sorting", "pixel sort effect", "glitch art", "Ether-MOSH Pixel Sort", "how to pixel sort", "real-time GPU effects"],
    tldr: "Pixel sorting reorders selected pixels along an axis according to brightness or color. Ether-MOSH uses a fast GPU interpretation: Threshold decides which luminance regions move, and Amount decides how far the horizontal smear travels.",
    satireDisclosure: "The department, workers, and labor dispute are fictional. The technique, controls, history, and production advice are real.",
    dispatch: [
      "At 08:14 this morning, the fictional Department of Pixel Labor announced that every bright pixel had been reassigned three hundred columns east. Dark pixels were told to remain calm and stop asking what happened to the cheekbone.",
      "Commissioner Gary Raster—an invented man with the confidence of a printer driver—called the streaking ‘a routine organizational event.’ He is lying. It is pixel sorting, it looks fantastic, and restraint is the only thing keeping your portrait from becoming artisanal horizontal soup.",
    ],
    explanation: [
      "Classic pixel sorting selects runs of pixels using a threshold, orders those pixels by a value such as brightness, and writes them back along a row or column. Kim Asendorf's 2010 ASDFPixelSort Processing script exposed white, black, bright, and dark threshold modes and helped establish the technique's modern visual vocabulary.",
      "Ether-MOSH is built for live performance, so its shader measures luminance, opens a soft gate around Threshold, and applies a noisy horizontal displacement scaled by Amount. You get the recognizable bright-region streaks at interactive speed, with the source still legible underneath.",
    ],
    steps: [
      "Open MOSH, load a high-contrast portrait, skyline, product image, or clip, then open the FX panel.",
      "Choose Data Corruption and add Pixel Sort. Start with Amount near 0.30 and Threshold near 0.55.",
      "Lower Threshold until the important highlights begin to streak. If the whole frame moves, crawl back from the ledge.",
      "Raise Amount for longer travel. Stack RGB Shift or Film Grain after it for separation and texture.",
      "Export a still for print, or record a short loop while animating one control slowly. One deliberate move beats twelve frantic knob confessions.",
    ],
    parameters: [
      { control: "Amount", purpose: "Distance and strength of the horizontal smear", low: "Source stays legible", high: "Long wrapping streaks", sweetSpot: "0.25–0.60" },
      { control: "Threshold", purpose: "Luminance gate deciding which regions move", low: "More of the frame qualifies", high: "Only bright regions qualify", sweetSpot: "0.35–0.65" },
      { control: "Source contrast", purpose: "Separation before the effect", low: "Soft cloudy movement", high: "Crisp streak boundaries", sweetSpot: "Strong subject edges" },
    ],
    uses: [
      { title: "Print + pattern", body: "Build a bold still and test a 3×3 repeat before committing to fabric or wallpaper. Streaks crossing a tile edge can become excellent seams or deeply stupid seams." },
      { title: "Projection + venue", body: "Use faces, architecture, or typography with obvious light-dark structure. Slow Amount changes read across a room; micro-jitter dies on the LED wall." },
      { title: "Vector + Lottie", body: "Pixel Sort is raster by nature. Trace only the strongest streak silhouettes for vector shapes, or feed a short high-contrast loop into a masked Lottie sticker." },
      { title: "Museum + education", body: "Compare MOSH output with the original ASDFPixelSort code to show how literal sorting and shader displacement can share a visual language while using different machinery." },
    ],
    quote: "Pixel sorting is not about destroying the image. It is about revealing the hierarchy the image was already hiding, then shoving that hierarchy sideways.",
    quoteAttribution: "The completely unauthorized MOSH field manual",
    downloadHref: "/news/downloads/pixel-sort-field-card.md",
    product: {
      name: "Liquid Glitch Beanie",
      href: "https://aestheticrebellion.store/products/liquid-glitch-beanie",
      copy: "Mandatory paid interruption: the Liquid Glitch Beanie at aestheticrebellion.store will not improve your threshold decisions. It will, however, make your skull look like it has better layer management. Capitalism has entered the tutorial wearing knitwear.",
    },
    sources: [
      { label: "Kim Asendorf — ASDFPixelSort", href: "https://github.com/kimasendorf/ASDFPixelSort", note: "Original 2010 Processing script and threshold modes." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current effect parameters, descriptions, and GLSL source." },
    ],
    relatedEffects: ["rgbShift", "filmGrain", "halftone", "photocopy"],
    faqs: [
      { question: "Is Ether-MOSH doing literal pixel sorting?", answer: "It is a real-time GPU interpretation. Luminance thresholds and horizontal displacement create the visual language without freezing live playback for a full CPU sort." },
      { question: "What images work best with Pixel Sort?", answer: "High-contrast portraits, architecture, night lights, bold type, and footage with clear silhouettes give the threshold useful structure to grab." },
      { question: "Can I use Pixel Sort for print?", answer: "Yes. Export a high-resolution still, inspect streak edges at 100%, proof the physical size, and use the print-ready 300 DPI export path." },
      { question: "Where is Pixel Sort in Ether-MOSH?", answer: "Open the FX panel, select Data Corruption, and add Pixel Sort. Desktop users can also open the command palette and search for it." },
    ],
  },
  {
    slug: "halftone-is-not-a-phase-mom",
    subjectKind: "effect",
    effectId: "halftone",
    effectName: "Halftone",
    category: "Print Crimes",
    title: "Halftone Is Not a Phase, Mom—Put These Dots Everywhere",
    dek: "How tiny ink dots faked continuous tone, conquered mass media, and escaped into your live visual stack wearing no pants and four process colors.",
    description: "Learn halftone printing history and practical Ether-MOSH Halftone settings for posters, patterns, motion graphics, projection, and print production.",
    publishedAt: "2026-08-31T08:05:00-07:00",
    readMinutes: 5,
    image: "/news/halftone-press-revolt.jpg",
    imageAlt: "A fictional historic print shop filled with cyan, magenta, yellow, and black halftone dots escaping from a screened portrait",
    imageCaption: "Management asked the dots to return to a regular screen. The magenta delegation demanded dental.",
    keywords: ["halftone effect", "halftone printing", "CMYK dots", "Ether-MOSH Halftone", "print design", "halftone tutorial"],
    tldr: "Halftoning simulates continuous tone with regularly spaced dots whose size carries tonal information. Ether-MOSH turns that print logic into an animated GPU effect; Amount blends it in and Dot Size moves from fine texture to giant graphic circles.",
    satireDisclosure: "The dot uprising and its labor demands are fictional. The print history, process explanation, MOSH controls, and production cautions are real.",
    dispatch: [
      "A fictional press foreman named Dolores Registration lost control of the cyan plate at lunch. By two o'clock magenta had unionized, yellow was inside the ventilation system, and black was carrying the composition while everybody else took credit.",
      "Traditional printing cannot lay down a smooth little fog of half-black ink on command. It prints ink or no ink. Tiny dots of changing size trick the eye into reading shades between those states.",
    ],
    explanation: [
      "The Library of Congress describes halftone photomechanical prints as reproductions distinguished by dot or line patterns created with a screen, used to reproduce continuous-tone originals such as photographs. Commercial halftone reproduction arrived in the 1880s and changed illustrated publishing.",
      "Process color separates cyan, magenta, yellow, and black screens at different angles. Ether-MOSH borrows that logic in a live three-channel shader and uses Dot Size plus Amount to move between photograph and graphic field.",
    ],
    steps: [
      "Load an image with simple lighting and recognizable midtones, then add Halftone from Color.",
      "Set Amount around 0.45 and Dot Size around 0.25 so the image remains a picture instead of becoming upholstery.",
      "Raise Dot Size for posters, projection, thumbnails, or coarse comic energy. Lower it for editorial texture and faces.",
      "Add Duotone to control the palette, or Photocopy after it for filthy repro edges.",
      "For print, export a proof and inspect it at final physical size. Your monitor is not your press and it has been lying to you since birth.",
    ],
    parameters: [
      { control: "Amount", purpose: "Blend between source and screened result", low: "Subtle print texture", high: "Dots dominate", sweetSpot: "0.40–0.78" },
      { control: "Dot Size", purpose: "Screen scale from fine to coarse", low: "Fine editorial screen", high: "Large graphic dots", sweetSpot: "Match output size" },
      { control: "Output scale", purpose: "How dots survive reproduction", low: "Fine detail may alias", high: "Coarse dots hold at distance", sweetSpot: "Proof at 100%" },
    ],
    uses: [
      { title: "Posters + packaging", body: "Use enough dot size to survive the final stock and viewing distance. A microscopic screen that vanishes in print is unpaid prepress performance art." },
      { title: "Patterns + textiles", body: "Large dots become repeat motifs; fine screens create texture. Test seams, garment scale, and separation before repeating the incident across six yards of polyester." },
      { title: "Projection + LED", body: "Coarser settings survive imperfect panels and distance. Animate Dot Size gently with bass for a breathing surface instead of a strobing eye exam." },
      { title: "Education + archives", body: "Compare a MOSH frame with a scanned newspaper under magnification: the same idea—tone encoded by marks—moves from print history into real-time graphics." },
    ],
    quote: "A halftone dot is a binary decision pretending to be nuance. Relatable, honestly.",
    quoteAttribution: "Dolores Registration, fictional foreman and real mood",
    downloadHref: "/news/downloads/halftone-field-card.md",
    product: {
      name: "Aesthetic Rebellion Word Cloud Bucket Hat",
      href: "https://aestheticrebellion.store/products/aesthetic-rebellion-word-cloud-bucket-hat",
      copy: "Aggressively visible sponsorship: aestheticrebellion.store would like to place the Aesthetic Rebellion Word Cloud Bucket Hat directly between you and financial maturity. It is reversible, because even product placement deserves two screen angles.",
    },
    sources: [
      { label: "Library of Congress — Halftone photomechanical prints", href: "https://www.loc.gov/pictures/item/tgm004832/", note: "Definition, reproduction use, and commercial-era context." },
      { label: "Adobe — Prepress terminology", href: "https://www.adobe.com/studio/print/pdf/prepress_terms.pdf", note: "Halftone screening and process-color dot arrays." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current parameters and shader source." },
    ],
    relatedEffects: ["duotone", "photocopy", "crossHatch", "moire"],
    faqs: [
      { question: "What is a halftone effect?", answer: "It represents continuous tones with discrete dots. Larger or denser dots read darker; smaller or separated dots read lighter." },
      { question: "Is MOSH Halftone a press-ready CMYK separation?", answer: "No. It is a live visual effect inspired by process-screen logic, not a replacement for professional separation, trapping, ink limits, or a physical proof." },
      { question: "What Dot Size should I use?", answer: "Use finer dots for detailed editorial texture and larger dots for posters, patterns, projections, or anything viewed at a distance." },
      { question: "Where is Halftone in Ether-MOSH?", answer: "Open the FX panel, select Color, and add Halftone. Its two controls are Amount and Dot Size." },
    ],
  },
  {
    slug: "make-moire-before-moire-makes-you-sick",
    subjectKind: "effect",
    effectId: "moire",
    effectName: "Moire",
    category: "Optical Incident",
    title: "Make Moire Before Moire Makes You Sick",
    dek: "Two innocent grids walk into a frame, disagree by four percent, and produce a giant beat pattern that now owns the venue.",
    description: "Understand moire interference and learn practical Ether-MOSH Moire settings for op art, projection mapping, live visuals, print proofs, patterns, and education.",
    publishedAt: "2026-08-31T08:10:00-07:00",
    readMinutes: 5,
    image: "/news/moire-optical-hearing.jpg",
    imageAlt: "A fictional optical hearing where overlapping fine line grids create a large moire wave behind a tribunal",
    imageCaption: "The tribunal ruled that the grids were individually harmless and collectively a pain in the ass.",
    keywords: ["moire effect", "moire pattern", "optical interference", "Ether-MOSH Moire", "op art", "projection mapping effects"],
    tldr: "Moire is a large interference pattern created when similar repeating grids overlap with a slight change in angle, spacing, or scale. Ether-MOSH animates two near-matching grids; Amount controls visibility and Pitch controls frequency.",
    satireDisclosure: "The Department of Optical Incidents and tribunal are fictional. The interference physics, cultural references, accessibility note, and MOSH workflow are real.",
    dispatch: [
      "The Department of Optical Incidents convened an emergency hearing after two grids were seen overlapping without a permit. Each looked boring alone. Together they generated a rolling wave large enough to swallow the municipal logo.",
      "Expert witness Dr. Patty Repeat—fabricated, overqualified, and furious—explained that nobody added the big wave. It emerged from the small mismatch between the patterns. The room requested a recess. The pattern requested a higher Pitch setting.",
    ],
    explanation: [
      "Moire appears when similar periodic structures overlap with a slight difference in angle, spacing, or scale. Their alignments create a larger beat pattern. It can be a camera or print artifact, a measurement tool, a material-science phenomenon, or the entire damn artwork.",
      "MoMA discusses optical interference in Liz Deschenes's Moire #25, while NIST describes moire in stacked atomic layers. Ether-MOSH recreates the mechanism with two fine grids: one rotates and runs at a slightly different frequency, producing a moving coarse field.",
    ],
    steps: [
      "Load a high-contrast image with broad shapes. Fine striped fabric may summon a second, less cooperative moire.",
      "Add Moire from Geometry. Begin with Amount around 0.25 and Pitch around 0.35.",
      "Increase Pitch until the grids resolve at your actual output size. Do not judge a venue loop in a postage-stamp preview like a tiny coward.",
      "Raise Amount until the pattern supports the source. Add Duotone for control or Bloom for luminous projection.",
      "Test on the real display, projector, camera, and print process. Resampling can create interference your laptop never showed you.",
    ],
    parameters: [
      { control: "Amount", purpose: "Visibility of the interference treatment", low: "Quiet shimmer", high: "Pattern dominates", sweetSpot: "0.18–0.62" },
      { control: "Pitch", purpose: "Frequency of the two source grids", low: "Broad calm structure", high: "Dense volatile field", sweetSpot: "Output-dependent" },
      { control: "Scale + camera", purpose: "Adds sensor and resampling interactions", low: "Stable in one context", high: "Secondary moire", sweetSpot: "Test final hardware" },
    ],
    uses: [
      { title: "Live installation", body: "Project onto simple surfaces first, then introduce architecture. Slow Pitch changes make a static wall feel volumetric without requiring a headset waiver." },
      { title: "Print + pattern", body: "Use moire intentionally only after physical proofing. The press, paper, screen ruling, scanner, and social thumbnail may each generate their own opinion." },
      { title: "Motion + performance", body: "Map Amount conservatively to audio and let Pitch drift. Rapid high-contrast changes can be uncomfortable, so keep an accessible low-intensity state." },
      { title: "Museum + education", body: "Layer two printed transparencies and rotate one by hand, then compare the analog beat pattern with Ether-MOSH. The principle becomes obvious without a paragraph wearing a lab coat." },
    ],
    quote: "Moire is what happens when repetition develops a disagreement and makes it everybody's problem.",
    quoteAttribution: "Dr. Patty Repeat, not a real doctor or person",
    downloadHref: "/news/downloads/moire-field-card.md",
    product: {
      name: "Chromatic Sweep Reversible Bucket Hat",
      href: "https://aestheticrebellion.store/products/chromatic-sweep-reversible-bucket-hat",
      copy: "Here comes the shameless sponsorship beam: the Chromatic Sweep Reversible Bucket Hat from aestheticrebellion.store contains enough competing color movement to make a moire grid file a restraining order. Please admire the nerve of inserting a hat into optical science.",
    },
    sources: [
      { label: "MoMA — Surface and Light: Liz Deschenes", href: "https://www.moma.org/explore/inside_out/2012/07/12/surface-and-light-liz-deschenes/", note: "Moiré as interference, misregistration, and photographic artwork." },
      { label: "NIST — Moiré Patterns Open Up More Possibilities", href: "https://www.nist.gov/news-events/news/2019/02/moire-patterns-open-more-possibilities-quantum-information", note: "Interference from overlaid periodic structures in material science." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current parameters and shader source." },
    ],
    relatedEffects: ["halftone", "duotone", "bloom", "feedbackTunnel"],
    faqs: [
      { question: "What causes a moire pattern?", answer: "Two similar repeating patterns overlap with a small difference in angle, spacing, or scale. Their periodic alignments form a larger visible beat pattern." },
      { question: "Is moire always a mistake?", answer: "No. It can be an unwanted artifact, but artists, designers, scientists, and engineers also use it intentionally." },
      { question: "Can I print MOSH Moire artwork?", answer: "Yes, but proof it physically. Scaling, screen ruling, paper, camera sensors, and later resampling can introduce additional interference." },
      { question: "Where is Moire in Ether-MOSH?", answer: "Open the FX panel, select Geometry, and add Moire. Start at low Amount and adjust Pitch at final output size." },
    ],
  },
  {
    slug: "break-the-keyframes-before-lunch",
    subjectKind: "effect",
    effectId: "datamosh",
    effectName: "Datamosh",
    category: "Codec Misconduct",
    title: "Break the Keyframes Before Lunch",
    dek: "Your video is too stable, the group chat prefers the broken cut, and compression has finally become a creative collaborator instead of a tiny bureaucrat in your export window.",
    description: "Learn how datamoshing uses video-compression logic and how to control Ether-MOSH Datamosh for loops, live visuals, music videos, projections, and print stills.",
    publishedAt: "2026-09-01T08:00:00-07:00",
    readMinutes: 5,
    image: "/news/datamosh-keyframe-intervention.jpg",
    imageAlt: "Friends in an apartment react to a birthday video breaking into bright datamosh blocks on a monitor",
    imageCaption: "The birthday edit broke at 1:17 a.m. Nobody fixed it because, for once, the group chat had excellent notes.",
    keywords: ["datamosh effect", "how to datamosh", "video compression glitch", "Ether-MOSH Datamosh", "motion vectors", "glitch video"],
    tldr: "Classic datamoshing exploits dependencies between compressed video frames so motion data affects the wrong picture. Ether-MOSH makes a live visual interpretation: Amount decides how many blocks move and how far, while Block Size controls the chunks.",
    satireDisclosure: "The apartment emergency is fictional. The compression concepts, MOSH controls, and production advice are real.",
    dispatch: [
      "You are making a birthday edit for a friend. The clean version is sincere, competent, and dead behind the eyes. Then playback hiccups, a face drags through the kitchen wall, and five people immediately yell, ‘Keep that.’ This is how an accident gets promoted above you.",
      "Datamoshing became beloved because compressed video already contains weird relationships between complete images, predicted changes, and motion. Break the relationship on purpose and movement starts borrowing the wrong body. It is technically rude and visually generous.",
    ],
    explanation: [
      "Many video codecs use full image frames alongside predicted frames that store changes relative to other frames. Classic datamoshing removes, rearranges, or misuses those reference points so motion information carries old imagery into new movement.",
      "Ether-MOSH does not corrupt an encoded file. Its real-time shader divides the picture into blocks, chooses changing regions, and offsets them as Amount rises. The result speaks the same block-reuse dialect while staying responsive enough to perform live.",
    ],
    steps: [
      "Load a clip with obvious movement: dancing, camera pans, hands, traffic, or somebody entering frame with unnecessary confidence.",
      "Open Data Corruption and add Datamosh. Start Amount near 0.35 and Block Size near 0.025.",
      "Raise Amount until motion begins stealing chunks of the frame. Stop before every subject becomes the same rectangular weather event.",
      "Increase Block Size for chunky poster-like damage; lower it when faces and gestures still need to read.",
      "Record a short loop through a strong movement change. For print, export the one frame where the smear has structure instead of merely evidence.",
    ],
    parameters: [
      { control: "Amount", purpose: "How many blocks move and how far", low: "Occasional slips", high: "Near-total block migration", sweetSpot: "0.30–0.68" },
      { control: "Block Size", purpose: "Scale of reused image chunks", low: "Fine digital chatter", high: "Large graphic slabs", sweetSpot: "0.015–0.040" },
      { control: "Source motion", purpose: "Gives displacement a readable event", low: "Texture more than action", high: "Clear trails and handoffs", sweetSpot: "One bold movement" },
    ],
    uses: [
      { title: "Music video + social", body: "Cut a clean performance into brief mosh handoffs. Two strong failures feel authored; forty seconds of soup feels like the laptop won." },
      { title: "Projection + VJ", body: "Use broad movement and medium blocks so the damage survives distance. Trigger Amount on transitions instead of stapling it to every kick." },
      { title: "Print + cover art", body: "Capture a frame where a block edge reinforces the composition, then use the print-ready export. Compression history is allowed on paper." },
      { title: "Teaching compression", body: "Compare a literal encoded-file datamosh with the MOSH shader. One alters codec dependencies; the other performs their visual behavior in real time." },
    ],
    quote: "The clean cut explained the party. The broken cut remembered what it felt like.",
    quoteAttribution: "A friend who accidentally gave the correct edit note",
    downloadHref: "/news/downloads/datamosh-field-card.md",
    product: {
      name: "Liquid Glitch Snapback",
      href: "https://aestheticrebellion.store/products/liquid-glitch-snapback",
      copy: "aestheticrebellion.store has inserted the Liquid Glitch Snapback here because your motion vectors needed a hat. It cannot repair a codec. It can make you look suspiciously calm while the footage dissolves.",
    },
    sources: [
      { label: "Adobe Media Encoder reference", href: "https://helpx.adobe.com/en/pdf/cs6/mediaencoder_reference.pdf", note: "Reference definitions for I, P, and B frames and keyframe intervals." },
      { label: "FFmpeg codec documentation", href: "https://www.ffmpeg.org/ffmpeg-codecs.html", note: "Technical reference for keyframes, reference frames, and motion-vector controls." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current Datamosh controls and shader implementation." },
    ],
    relatedEffects: ["blockShift", "compressionTears", "rgbShift", "filmGrain"],
    faqs: [
      { question: "Is Ether-MOSH literally corrupting my video file?", answer: "No. It performs a responsive GPU interpretation of datamosh block reuse; your source file remains intact." },
      { question: "What footage works best?", answer: "Clips with clear motion, cuts, pans, gestures, or subjects crossing the frame make displaced blocks easier to read." },
      { question: "What does Block Size change?", answer: "It changes the scale of the sampled chunks, from fine digital chatter to large graphic blocks." },
      { question: "Where is Datamosh?", answer: "Open the FX panel, choose Data Corruption, and add Datamosh. Its live controls are Amount and Block Size." },
    ],
  },
  {
    slug: "your-fake-crt-looks-cheap",
    subjectKind: "effect",
    effectId: "crtPhosphor",
    effectName: "CRT",
    category: "Retro Intervention",
    title: "Your Fake CRT Looks Cheap—Stop at the Scanlines",
    dek: "A tube display is curved glass, phosphors, masks, bloom, and decades of accumulated emotional baggage. Three gray lines over a clean render are not fooling anybody.",
    description: "Learn how CRT displays form images and how to use Ether-MOSH CRT Curvature, Shadow Mask, and Bloom for live visuals, motion design, installations, and print.",
    publishedAt: "2026-09-01T08:05:00-07:00",
    readMinutes: 5,
    image: "/news/crt-scanline-intervention.jpg",
    imageAlt: "A tired VJ sits beside a glowing curved CRT while a creative director holds a retro moodboard",
    imageCaption: "The brief said ‘retro.’ The television arrived with actual structure and immediately became difficult to manage.",
    keywords: ["CRT effect", "CRT phosphor", "shadow mask", "Ether-MOSH CRT", "retro video effect", "scanline effect"],
    tldr: "A CRT scans an electron beam across phosphors behind curved glass, with a shadow mask or grille helping steer color. Ether-MOSH models the look with Curvature, Shadow Mask, and Bloom—not a lonely scanline overlay wearing nostalgia as a fake mustache.",
    satireDisclosure: "The creative director and workplace tension are fictional. The display principles, controls, and production cautions are real.",
    dispatch: [
      "A creative director leans over your shoulder and says, ‘Can you make it more old TV?’ You add scanlines. They nod for seven seconds, then ask why it still looks like a new video wearing blinds. This is annoying because they are right.",
      "A real cathode-ray tube is a physical imaging system: beam, phosphors, glass geometry, color structure, glow, and imperfect edges. The look came from hardware doing its job, not an opacity layer named FINAL_crt_07.",
    ],
    explanation: [
      "Inside a color CRT, electron guns aim beams toward red, green, and blue phosphors. A shadow mask or aperture grille helps each beam reach the intended color structure, while the scan and phosphor response build the visible image across the tube.",
      "Ether-MOSH bends the source as if it sits on curved glass, overlays a fine RGB phosphor structure, and adds controlled glow. Curvature establishes the object; Shadow Mask establishes the surface; Bloom lets bright areas bleed without turning the frame into a scented candle.",
    ],
    steps: [
      "Load footage with bright edges, faces, typography, game graphics, or a dark background that gives glow somewhere to exist.",
      "Add CRT from Atmosphere. Start Curvature at 0.30, Shadow Mask at 0.45, and Bloom at 0.25.",
      "Set Curvature first. If the picture looks trapped in a novelty fisheye, lower it and apologize to the corners.",
      "Raise Shadow Mask while viewing at final display size. Too fine can alias; too strong can chew through detail.",
      "Add Bloom last, then test the actual projector, LED wall, phone, or export. Different resampling produces different tiny lies.",
    ],
    parameters: [
      { control: "Curvature", purpose: "Bends the image toward tube geometry", low: "Mostly flat panel", high: "Pronounced barrel shape", sweetSpot: "0.20–0.48" },
      { control: "Shadow Mask", purpose: "Strength of the RGB phosphor structure", low: "Soft texture", high: "Visible color grille", sweetSpot: "0.35–0.65" },
      { control: "Bloom", purpose: "Bleed around bright phosphors", low: "Crisp and dry", high: "Soft luminous spill", sweetSpot: "0.18–0.45" },
    ],
    uses: [
      { title: "Venue visuals", body: "CRT can make pristine playback feel physical. Keep the mask broad enough to survive the LED processor instead of fighting a pixel grid with another pixel grid." },
      { title: "Games + motion graphics", body: "Use Curvature and Bloom to frame menus or simulated broadcasts, then reserve stronger masks for close-ups and transitions." },
      { title: "Print + editorial", body: "Export a still with readable phosphor structure and proof it at size. Fine stripes can become accidental moire when reduced." },
      { title: "Exhibition + archive", body: "Pair the effect with photographs of real CRT subpixels to discuss how display hardware becomes an aesthetic after the hardware disappears." },
    ],
    quote: "Scanlines are a symptom. The tube is the whole strange little body.",
    quoteAttribution: "The venue tech who has carried enough televisions",
    downloadHref: "/news/downloads/crt-field-card.md",
    product: {
      name: "Channel Static Hoodie",
      href: "https://aestheticrebellion.store/products/channel-static-hoodie",
      copy: "This lesson is interrupted by the Channel Static Hoodie at aestheticrebellion.store, a garment scientifically unable to make your scanlines more authentic but extremely willing to stand near a television and take credit.",
    },
    sources: [
      { label: "iFixit — CRT Displays", href: "https://www.ifixit.com/Wiki/CRT_Displays", note: "Overview of electron guns, phosphors, shadow masks, aperture grilles, and raster scanning." },
      { label: "Sarnoff Collection — First Shadow Mask CRT", href: "https://embark.tcnj.edu/objects-1/info/126?objectName=First+Shadow+Mask+Cathode+Ray+Tube+%28CRT%29&sort=0", note: "Museum object record for early color shadow-mask tube development." },
      { label: "Ether-MOSH Effect Registry", href: "/effects", note: "Current CRT parameters and shader source." },
    ],
    relatedEffects: ["vhsBleed", "filmGrain", "chromaAberrate", "vignette"],
    faqs: [
      { question: "Is a CRT look just scanlines?", answer: "No. Tube curvature, phosphor color structure, mask or grille behavior, glow, and edge response are all part of the display's visual character." },
      { question: "Why does the mask shimmer after export?", answer: "Fine repeated stripes can alias during scaling or compression. Judge them at final size and reduce Shadow Mask when needed." },
      { question: "Can CRT work in print?", answer: "Yes, but proof the physical output because phosphor stripes can merge or form unintended moire after resampling." },
      { question: "Where is CRT?", answer: "Open the FX panel, choose Atmosphere, and add CRT. Its controls are Curvature, Shadow Mask, and Bloom." },
    ],
  },
  {
    slug: "forge-mode-already-started-the-fight",
    subjectKind: "mode",
    effectName: "Forge Mode",
    category: "Mode Manual",
    title: "Forge Mode Already Started the Fight",
    dek: "Stop choosing every pixel like a middle manager. Give the generator a direction, let six visual systems argue, and intervene when the argument gets good.",
    description: "Learn how Ether-MOSH Forge Mode combines six seeded procedural generators, effect stacks, crossfades, audio response, seamless controls, and print-ready exports.",
    publishedAt: "2026-09-01T08:10:00-07:00",
    readMinutes: 5,
    image: "/news/forge-mode-six-generators.jpg",
    imageAlt: "An artist smiles at a workstation surrounded by six distinct procedural visual worlds",
    imageCaption: "The machine made six suggestions. For once, none of them began with ‘make the logo bigger.’",
    keywords: ["Ether-MOSH Forge Mode", "generative art tool", "procedural visuals", "reaction diffusion art", "VJ generator", "print ready generative art"],
    tldr: "Forge Mode is Ether-MOSH's seeded procedural source. It rotates through six generators, composes effect stacks, crossfades between states, reacts to audio, accepts optional image material, and can output seamless or print-ready art without requiring a source clip.",
    satireDisclosure: "No generator achieved sentience or filed a complaint. The six systems, mode behavior, controls, and export details are real.",
    dispatch: [
      "You open MOSH with no footage and the mild panic of a person who promised visuals before finding visuals. Forge does not ask for a moodboard. It starts growing blobs, fields, cracks, contours, and chemical-looking organisms while you decide which accident deserves custody.",
      "That is the useful division of labor: the system proposes, you judge. A seed keeps a direction reproducible, transitions keep changes from arriving like a folding chair, and the normal MOSH stack remains available when a generator needs tasteful damage.",
    ],
    explanation: [
      "Forge includes Volumetric Bloom, Drift Field, Shatter Field, Pour Bloom, Contour Bands, and a stateful Gray-Scott Reaction Diffusion simulation. Each generator has its own structure, then a shared finishing pass and MOSH effect stack give the family a related visual language.",
      "Shuffle can change the generator and stack while a 2.4-second crossfade carries the previous state into the next. Seeds, palette direction, intensity, audio response, optional base imagery, mosaic density, overlay, kaleidoscope, and seamless constraints let you guide the system without drawing every cell by hand.",
    ],
    steps: [
      "Open the source selector and choose the Flame icon labeled Forge. No upload is required.",
      "Shuffle until the generator family suits the job, then set Intensity before decorating the stack into witness protection.",
      "Turn on audio response for performance, or leave it off when you need a stable print composition.",
      "Add a base image and mosaic overlay when the abstract field needs memory of a photograph. Enable Seamless before composing a repeat.",
      "Export a loop, still, seamless tile, or a 2048–8000 px print-ready PNG stamped at your selected DPI.",
    ],
    parameters: [
      { control: "Generator + seed", purpose: "Chooses a visual system and repeatable state", low: "One held direction", high: "Frequent evolution", sweetSpot: "Hold after a strong draw" },
      { control: "Intensity", purpose: "Pushes generator and effect-stack behavior", low: "Sparse and legible", high: "Dense and unruly", sweetSpot: "0.42–0.72" },
      { control: "Seamless + overlay", purpose: "Prepares repeats or mixes source material", low: "Pure procedural source", high: "Image-led construction", sweetSpot: "Job-dependent" },
    ],
    uses: [
      { title: "Live visuals", body: "Let generator changes crossfade instead of hard-cutting every bar. Audio response is a collaborator, not a court order to wiggle everything." },
      { title: "Album + campaign systems", body: "Reuse one seed and palette across covers, clips, and social crops so the family feels related without becoming identical triplets." },
      { title: "Print + textile", body: "Freeze a strong state, enable seamless constraints for repeats, and export at the final pixel target. Proof before manufacturing a very expensive argument." },
      { title: "Education + installation", body: "Compare field, cellular, contour, metaball, and reaction-diffusion systems to show how different algorithms produce different kinds of organic structure." },
    ],
    quote: "Generative art is not pressing a button. It is knowing which result earned the right to stay.",
    quoteAttribution: "The operator, still employed for judgment",
    downloadHref: "/news/downloads/forge-mode-field-card.md",
    product: {
      name: "Prism Facet Mosaic V-Neck Top",
      href: "https://aestheticrebellion.store/products/prism-facet-mosaic-v-neck-top",
      copy: "Forge would like to disclose a shameless internal sponsorship by the Prism Facet Mosaic V-Neck Top at aestheticrebellion.store. It is what happens when a procedural field gets payroll, fabric, and absolutely no request to calm down.",
    },
    sources: [
      { label: "V&A — Digital Art", href: "https://www.vam.ac.uk/articles/digital-art", note: "Historical context for computer-generated, algorithmic, and interactive artwork." },
      { label: "Ether-MOSH effects library", href: "/effects", note: "The effects Forge can compose over its procedural source." },
      { label: "Open Forge Mode", href: "/edit", note: "Current generators, controls, transitions, and export workflow." },
    ],
    relatedEffects: ["bloom", "liquidWarp", "kaleidoscope", "filmGrain"],
    faqs: [
      { question: "Does Forge Mode need a photo or video?", answer: "No. It can generate a complete procedural source by itself, with optional imagery when you want to mix in recognizable material." },
      { question: "How many generators are in Forge?", answer: "Six: Volumetric Bloom, Drift Field, Shatter Field, Pour Bloom, Contour Bands, and Reaction Diffusion." },
      { question: "Can Forge make seamless patterns?", answer: "Yes. Enable Seamless before generating and inspect a repeat proof before production." },
      { question: "Can I reproduce a result?", answer: "The seed preserves the underlying direction; keep it and your settings when you need a related version later." },
    ],
  },
  {
    slug: "stop-gaslighting-the-seam",
    subjectKind: "mode",
    effectName: "Pattern / Motif Mode",
    category: "Mode Manual",
    title: "Your Pattern Doesn't Tile—Stop Gaslighting the Seam",
    dek: "That vertical scar is not ‘organic variation.’ Pattern mode lives under Motif, and it has a repeat proof specifically so the seam can be confronted before it reaches upholstery.",
    description: "Learn how Ether-MOSH Pattern mode, labeled Motif and Motif Maestro, builds seamless tiles and repeat proofs from Forge, uploaded images, or camera stills.",
    publishedAt: "2026-09-01T08:15:00-07:00",
    readMinutes: 5,
    image: "/news/pattern-mode-seam-hearing.jpg",
    imageAlt: "A textile designer points at a seam in a bold mirrored repeating pattern across fabric and wallpaper",
    imageCaption: "The seam claimed it was part of the concept. The three-by-three repeat proof produced receipts.",
    keywords: ["Ether-MOSH pattern mode", "Motif Maestro", "seamless pattern generator", "repeat tile", "textile pattern design", "seamless PNG"],
    tldr: "Pattern mode appears as Motif in the source selector. Motif Maestro can use Forge, an upload, or a camera still; forces seamless mirror tiling by default; controls direction, symmetry, density, and variation; and exports either a 2048 px tile or a 3×3 repeat proof with print DPI metadata.",
    satireDisclosure: "The seam hearing is fictional. The Motif controls, repeat workflow, export behavior, and production cautions are real.",
    dispatch: [
      "You make a beautiful tile. You duplicate it once. A hard vertical seam appears with the confidence of a landlord asking for another deposit. You zoom in, call it texture, zoom out, and discover texture has formed a fence.",
      "Pattern mode exists because a single attractive square is not yet a pattern. Repetition creates new shapes, new spacing, and new failures. Motif Maestro makes those relationships visible before your printer makes them expensive.",
    ],
    explanation: [
      "In the current interface, Pattern mode is labeled Motif and opens the Motif Maestro workspace. It accepts a Forge source, uploaded image, or camera still, then builds directional repeats using mirror, rotate, or kaleidoscope symmetry with adjustable density and variation.",
      "The workspace starts with Seamless and mirror tiling enabled, generates a 2048 px motif tile, and can assemble a 3×3 repeat proof. The readout scores seamlessness, composition, contrast, and motif strength so you can inspect the system—not just admire one square in isolation.",
    ],
    steps: [
      "Choose the Sparkles source labeled Motif. If you were looking for a button named Pattern, congratulations: this sentence saved a search party.",
      "Choose Forge, Upload, or Camera as the source, then pick all-direction, horizontal, or vertical movement.",
      "Set symmetry to mirror, rotate, or kaleidoscope. Adjust Density for spacing and Variation for how far the arrangement evolves.",
      "Generate, inspect the readout, then view the 3×3 proof. Look at every edge and the larger accidental shapes formed by repetition.",
      "Export the 2048 px tile or repeat proof with your selected print DPI, then test it at the real product scale.",
    ],
    parameters: [
      { control: "Direction", purpose: "Organizes motif flow across the repeat", low: "Single-axis order", high: "All-direction movement", sweetSpot: "Match the product shape" },
      { control: "Symmetry", purpose: "Mirror, rotate, or kaleidoscope tiling", low: "Readable repetition", high: "Dense radial structure", sweetSpot: "Mirror first" },
      { control: "Density + variation", purpose: "Controls spacing and evolutionary distance", low: "Airy and consistent", high: "Crowded and surprising", sweetSpot: "Proof at final scale" },
    ],
    uses: [
      { title: "Fabric + apparel", body: "Use the repeat proof to catch seams, scale problems, and accidental focal points before one weird flower lands on every left armpit." },
      { title: "Wallpaper + interiors", body: "Judge the larger rhythm across several tiles. A repeat that looks balanced on a laptop can become a marching column across a wall." },
      { title: "Packaging + identity", body: "Hold the seed, symmetry, and palette to create a recognizable system across boxes, tissue, labels, and campaign backgrounds." },
      { title: "Education + sampling", body: "Compare mirror, rotate, and kaleidoscope proofs from the same source to show how repeat logic changes composition without changing the motif itself." },
    ],
    quote: "A seamless tile hides the join. A good pattern makes you stop looking for it.",
    quoteAttribution: "The repeat proof, finally allowed to testify",
    downloadHref: "/news/downloads/pattern-mode-field-card.md",
    product: {
      name: "Seamless Patterns SVG Bundle — 800+ Cut Files",
      href: "https://aestheticrebellion.store/products/seamless-patterns-svg-bundle-800-cut-files",
      copy: "Subtlety has left the building: aestheticrebellion.store sells a Seamless Patterns SVG Bundle with more than 800 cut files, placed here directly in front of your face because even satire understands inventory alignment.",
    },
    sources: [
      { label: "Adobe Illustrator — Create a pattern", href: "https://www.adobe.com/learn/illustrator/web/create-pattern", note: "Practical reference for repeat tiles, spacing, scale, brick, and half-drop structures." },
      { label: "Adobe Illustrator — Repeat patterns overview", href: "https://helpx.adobe.com/in/illustrator/desktop/paint-and-fill/create-and-edit-patterns/repeat-patterns-overview.html", note: "Reference for grid, radial, and mirror repeat systems." },
      { label: "Open Motif Maestro", href: "/edit", note: "Current source, direction, symmetry, density, variation, proof, and export controls." },
    ],
    relatedEffects: ["kaleidoscope", "mirrorKaleido", "moire", "halftone"],
    faqs: [
      { question: "Where is Pattern mode in Ether-MOSH?", answer: "It is labeled Motif in the source selector. Choose the Sparkles icon to open Motif Maestro." },
      { question: "What can I use as a pattern source?", answer: "Forge output, an uploaded still image, or a camera still." },
      { question: "What is a repeat proof?", answer: "It places the tile in a larger grid so seams, spacing, and accidental shapes become visible before production." },
      { question: "What does Motif export?", answer: "A 2048 px seamless tile or a 3×3 repeat proof PNG with the selected print DPI metadata." },
    ],
  },
  {
    slug: "turn-the-kaleidoscope-effect-until-it-confesses",
    subjectKind: "effect",
    effectId: "kaleidoscope",
    effectName: "Kaleidoscope",
    category: "Optical Misconduct",
    title: "Turn the Kaleidoscope Effect Until the Room Confesses",
    dek: "Two controls, one folding chair, and enough radial symmetry to make a venue inspector question whether furniture has achieved collective consciousness.",
    description: "Learn how the kaleidoscope effect uses mirrored radial symmetry and how to set Ether-MOSH Segments and Spin for patterns, motion, projection, print, and education.",
    publishedAt: "2026-09-01T09:15:00-07:00",
    readMinutes: 5,
    image: "/news/kaleidoscope-venue-inspection.jpg",
    imageAlt: "A fictional venue inspector beside a folding chair as the chair repeats into a static acid-green, magenta, and cyan kaleidoscope projection",
    imageCaption: "The chair passed inspection. Its sixteen reflected cousins are waiting on separate paperwork.",
    keywords: ["kaleidoscope effect", "Ether-MOSH Kaleidoscope", "radial mirror effect", "kaleidoscope tutorial", "projection visuals", "seamless pattern design", "accessible motion graphics"],
    tldr: "The kaleidoscope effect turns one image into rotating radial mirror symmetry. Ether-MOSH converts the frame to polar space, divides it with Segments, folds each wedge, then samples the source; Spin rotates the fold over time. Start at 6 Segments and 0.15 Spin. Use 0 Spin for a static or lower-motion result.",
    satireDisclosure: "The venue inspection, inspector Mara Wedge, and multiplying-chair incident are fictional. The optical history, Ether-MOSH controls, shader behavior, accessibility guidance, and production advice are factual and sourced.",
    dispatch: [
      "At 09:15, fictional venue inspector Mara Wedge entered Studio B and found one folding chair reflected into a radial committee of sixteen. The committee had no permit, no fire marshal, and one aggressively centered vanishing point.",
      "Wedge asked the projection operator to stop the rotation. The operator set Spin to zero, the chair caucus froze, and everybody discovered that a kaleidoscope can be dramatic without moving like it owes the room money.",
    ],
    explanation: [
      "David Brewster's 1817 British patent 4136 describes a new optical instrument called the kaleidoscope for creating forms and patterns useful to the ornamental arts. A National Museums Scotland instrument from about 1820 uses reflection to create multiple images and identifies Brewster as its designer; a University of St Andrews museum record documents another Brewster patent kaleidoscope dated 1816–1830.",
      "Ether-MOSH recreates the visual logic rather than simulating physical glass. Its shader converts each pixel position to an angle and radius, divides the circle by Segments, mirrors every angular wedge, and samples the source at the folded coordinate. Spin adds a continuous angular offset; at 0, the fold stays still.",
      "Kaleidoscope does not generate flashes by itself, but fast rotation, high contrast, and flashing effects elsewhere in a stack can still be uncomfortable. Keep public-facing motion slow, provide a static option when practical, and test any flashing output against WCAG's three-flashes-or-below-threshold guidance.",
    ],
    steps: [
      "Load an asymmetrical image or clip with one strong off-center subject, then open the FX panel and add Kaleidoscope from Geometry.",
      "Set Segments to 6 and Spin to 0.15. Six wedges keep the source recognizable while the slow turn makes the fold easy to read.",
      "Try 2–4 Segments for bold reflected architecture, or 8–12 for a denser mandala. The available range is 2–16; more is not automatically more employed.",
      "Set Spin to 0 for print, a held installation state, or a lower-motion version. For venues, keep motion deliberate and avoid stacking rapid flashes or hard luminance cuts.",
      "Export a still or short loop. For fabric or wallpaper, use the still as a Motif source and inspect the 3×3 repeat proof before manufacturing a radial seam emergency.",
    ],
    parameters: [
      { control: "Segments", purpose: "Divides the circle into mirrored angular wedges", low: "2–4 bold reflections", high: "12–16 dense symmetry", sweetSpot: "6" },
      { control: "Spin", purpose: "Rotates the folded sampling angle over time", low: "0 static; 0.05 gentle", high: "1 fast rotation", sweetSpot: "0.15" },
      { control: "Source framing", purpose: "Determines what each wedge repeats", low: "Centered source feels regular", high: "Off-center detail creates movement", sweetSpot: "One clear asymmetry" },
    ],
    uses: [
      { title: "Print + pattern", body: "Freeze Spin, export a strong still, then bring it into Motif Maestro for a repeat proof. Check the center, corners, and product scale before the mandala colonizes a duvet." },
      { title: "Vector + Lottie", body: "Trace a few dominant wedge boundaries instead of every raster detail, or use a short low-Spin loop as a masked motion layer. Simpler symmetry survives small screens and lightweight animation." },
      { title: "Projection + venue", body: "Use architecture, dancers, props, or logos with a readable silhouette. Keep rotation slow, rehearse at full screen brightness, and offer a static cue for motion-sensitive audiences." },
      { title: "Museum + education", body: "Place a physical two-mirror kaleidoscope beside the shader output to compare reflected light with coordinate folding. The pictures rhyme; the machinery does not." },
    ],
    quote: "Radial symmetry is what happens when one image gets a committee and every member insists on facing the center.",
    quoteAttribution: "Mara Wedge, fictional inspector of repeat offenses",
    downloadHref: "/news/downloads/kaleidoscope-field-card.md",
    product: {
      name: "Radial Kaleidoscope Aloha Shirt",
      href: "https://aestheticrebellion.store/products/radial-kaleidoscope-aloha-shirt",
      copy: "This science lesson is now being mugged by commerce: the Radial Kaleidoscope Aloha Shirt at aestheticrebellion.store puts green, purple, and rainbow radial tile bursts on a camp-collar shirt. Buying it will not improve Segments. It may, however, make your torso look peer-reviewed by a disco ball.",
    },
    sources: [
      { label: "University of St Andrews — Telescopic kaleidoscope", href: "https://collections.st-andrews.ac.uk/item/telescopic-kaleidoscope/1000356", note: "Museum record for a Brewster patent kaleidoscope dated 1816–1830." },
      { label: "National Museums Scotland — Telescopic kaleidoscope", href: "https://www.nms.ac.uk/collections/search/object?creator=Brewster%2C+David%2C+Sir%2C+1781+-+1868&entry=222186&page=1&view=cards", note: "Museum record for a reflection-based instrument designed by Brewster around 1820." },
      { label: "David Brewster — 1817 patent specification", href: "https://brewstersociety.com/pdf/brewster_patent.pdf", note: "Primary patent text describing the optical instrument and ornamental patterns." },
      { label: "W3C — Three Flashes or Below Threshold", href: "https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold", note: "Current accessibility guidance for evaluating flashing content." },
      { label: "Ether-MOSH Kaleidoscope registry entry", href: "/effects#kaleidoscope", note: "Current Geometry category, Segments and Spin ranges, defaults, and GLSL source." },
      { label: "Pattern Mode field report", href: "/news/stop-gaslighting-the-seam", note: "Internal guide for turning a Kaleidoscope still into a proofed repeat." },
      { label: "Moire field report", href: "/news/make-moire-before-moire-makes-you-sick", note: "Related optical-pattern guide with projection and accessibility cautions." },
    ],
    relatedEffects: ["mirror", "polarFold", "moire", "twirl"],
    faqs: [
      { question: "What does the kaleidoscope effect do?", answer: "It folds an image into mirrored radial wedges around the center, creating repeated symmetry from one source frame." },
      { question: "Where is Kaleidoscope in Ether-MOSH?", answer: "Open the FX panel, choose Geometry, and add Kaleidoscope. Its controls are Segments from 2–16 and Spin from 0–1." },
      { question: "What is a good Kaleidoscope Segments setting?", answer: "Start at 6. Use 2–4 for large readable reflections and 8–12 for a denser mandala, then judge at the final output size." },
      { question: "How do I use a kaleidoscope effect safely in projection?", answer: "Keep Spin slow, avoid rapid flashes and hard high-contrast cuts elsewhere in the stack, rehearse at full brightness, and provide a static version when practical." },
    ],
  },
  {
    slug: "posterize-the-image-before-the-gradient-files-a-complaint",
    subjectKind: "effect",
    effectId: "posterize",
    effectName: "Posterize",
    category: "Tonal Misconduct",
    title: "Posterize the Image Before the Gradient Files a Complaint",
    dek: "Levels cuts the tonal budget, Bias moves the layoffs, and your formerly smooth portrait would like a union representative before the next export.",
    description: "Learn how the posterize effect quantizes RGB tones and how to set Ether-MOSH Levels and Bias for posters, patterns, motion, projection, and accessible graphics.",
    publishedAt: "2026-09-01T09:36:00-07:00",
    readMinutes: 5,
    image: "/news/posterize-tonal-inspection.jpg",
    imageAlt: "A fictional tonal inspector watches a portrait pass through a posterize effect machine and emerge in flat yellow, magenta, blue, and black color bands",
    imageCaption: "The gradient submitted three hundred tonal levels. Municipal finance approved five and a clipboard.",
    keywords: ["posterize effect", "Ether-MOSH Posterize", "posterization tutorial", "tonal quantization", "flat color effect", "poster design", "GPU image effects"],
    tldr: "The posterize effect compresses smooth color into coarse tonal steps. Ether-MOSH quantizes each RGB channel with Levels from 2–16, while Bias shifts where those bands fall before quantization. Start at 5 Levels and 0.50 Bias. Lower Levels makes bolder blocks; moving Bias below or above 0.50 favors darker or lighter output.",
    satireDisclosure: "The municipal tonal inspector, gradient complaint, and color-budget hearing are fictional. The Adobe definition, Ether-MOSH controls and shader behavior, accessibility guidance, and production advice are factual and sourced.",
    dispatch: [
      "At 09:36, fictional tonal inspector Clive Banding rejected a portrait for containing ‘an administratively reckless number of transitions.’ He fed it into the city sorter, stamped five levels approved, and asked the highlights to vacate the premises by lunch.",
      "The gradient filed a complaint. Bias moved the hearing toward the shadows. Nobody won, but the image came out looking decisive enough to headline a poster and deny everything under oath.",
    ],
    explanation: [
      "Adobe defines its Posterize adjustment as choosing a number of tonal levels for each channel and mapping pixels to the closest matching level, producing large flat areas when the count is reduced. That is the useful core of posterization: fewer available tone steps make smooth transitions resolve into visible bands.",
      "Ether-MOSH performs a live GPU version. The shader shifts every RGB channel by Bias, clamps the result, multiplies by Levels, rounds downward, and divides again. Levels changes the step size from blunt blocks to finer bands; Bias moves the boundaries before the cut. This is per-channel color quantization, not a promise of an exact total palette size.",
      "Posterization can erase subtle boundaries as efficiently as it creates graphic ones. If the result contains essential labels, diagrams, or text, verify the final light-dark contrast rather than trusting saturated color; W3C guidance requires at least 4.5:1 for normal text and 3:1 for large text in typical cases.",
    ],
    steps: [
      "Load a portrait, architecture shot, product image, or clip with clear light and shadow, then add Posterize from Color in the FX panel.",
      "Set Levels to 5 and Bias to 0.50. This preserves enough facial and edge structure while making the tonal bands obvious.",
      "Lower Levels toward 2–4 for blunt screen-print shapes, or raise it toward 8–12 for quieter banding. Judge at the actual export or venue size.",
      "Move Bias below 0.50 to push more values into darker bands, or above 0.50 to lift them into lighter bands. Return to 0.50 when the composition starts looking financially manipulated.",
      "Export a still or short loop, then check gradients, faces, labels, and text at 100%. For print, proof the physical size; for projection, rehearse on the actual panel or projector.",
    ],
    parameters: [
      { control: "Levels", purpose: "Sets the size of the per-channel quantization steps", low: "2–4 bold flat blocks", high: "12–16 finer bands", sweetSpot: "5" },
      { control: "Bias", purpose: "Shifts tone values before they are quantized", low: "Darker band placement", high: "Lighter band placement", sweetSpot: "0.50" },
      { control: "Source lighting", purpose: "Determines which edges survive the reduced tone budget", low: "Soft forms may merge", high: "Hard light creates crisp regions", sweetSpot: "Clear subject separation" },
    ],
    uses: [
      { title: "Print + posters", body: "Use 3–6 Levels to find strong color regions, then proof at final size. The exported RGB image is artwork, not automatically a separated spot-color file, so involve the printer before declaring victory over ink." },
      { title: "Pattern + textiles", body: "Posterize a motif before tiling it to reduce visual mud across repeats. Inspect a 3×3 proof because one charming band edge can become a suspicious stripe across an entire duvet." },
      { title: "Vector + Lottie", body: "Trace the largest flat regions into vector shapes, or animate Bias slowly and export a short raster loop. Fewer regions create cleaner paths and lighter motion assets." },
      { title: "Projection + education", body: "Move Levels one step at a time to demonstrate quantization on a large screen. Keep instructional labels outside the effected layer and test their contrast independently." },
    ],
    quote: "A gradient is just a committee of tones. Posterize reduces the meeting until somebody finally makes a decision.",
    quoteAttribution: "Clive Banding, fictional municipal quantizer",
    downloadHref: "/news/downloads/posterize-field-card.md",
    product: {
      name: "Street Collage Full-Zip Hoodie",
      href: "https://aestheticrebellion.store/products/street-collage-full-zip-hoodie",
      copy: "Mandatory commerce break: the Street Collage Full-Zip Hoodie at aestheticrebellion.store layers torn-poster energy across an entire garment. It will not choose your Levels. It will make your torso look like the municipal notice board escaped zoning enforcement.",
    },
    sources: [
      { label: "Adobe — Apply special color effects in Photoshop", href: "https://helpx.adobe.com/photoshop/using/applying-special-color-effects-images.html", note: "Authoritative definition of posterization as mapping channel values to a chosen number of tonal levels." },
      { label: "W3C — Contrast (Minimum)", href: "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html", note: "Current guidance for readable light-dark contrast in text and images of text." },
      { label: "Ether-MOSH Posterize registry entry", href: "/effects#posterize", note: "Current Color category, Levels and Bias ranges, defaults, and shader source." },
      { label: "Halftone field report", href: "/news/halftone-is-not-a-phase-mom", note: "Related guide to translating tone into deliberately limited graphic marks." },
      { label: "Pattern Mode field report", href: "/news/stop-gaslighting-the-seam", note: "Internal guide for turning a simplified still into a proofed repeat." },
    ],
    relatedEffects: ["duotone", "halftone", "photocopy", "crtPhosphor"],
    faqs: [
      { question: "What does the posterize effect do?", answer: "It reduces smooth RGB tone changes to visible steps, creating flatter color regions and deliberate banding." },
      { question: "Where is Posterize in Ether-MOSH?", answer: "Open the FX panel, choose Color, and add Posterize. Its controls are Levels from 2–16 and Bias from 0–1." },
      { question: "What Posterize settings should I start with?", answer: "Start at 5 Levels and 0.50 Bias, then lower Levels for bolder blocks or move Bias slightly to rebalance shadows and highlights." },
      { question: "Is a posterized export ready for spot-color printing?", answer: "No. It is still an RGB raster result. Use it as artwork, then prepare actual separations, profiles, and proofs with your printer or prepress workflow." },
    ],
  },
  {
    slug: "make-the-duotone-effect-pick-a-side",
    subjectKind: "effect",
    effectId: "duotone",
    effectName: "Duotone",
    category: "Ink Relations",
    title: "Make the Duotone Effect Pick a Side",
    dek: "Two colors enter, luminance mediates, and your grayscale source leaves the press looking far more expensive than the meeting that approved it.",
    description: "Learn how the duotone effect maps image luminance between two colors and how to set Ether-MOSH Mix and Hue for print-inspired graphics, motion, and projection.",
    publishedAt: "2026-09-01T09:37:00-07:00",
    readMinutes: 5,
    image: "/news/duotone-ink-mediation.jpg",
    imageAlt: "A fictional print operator mediates between indigo and coral ink rollers as a grayscale portrait emerges with a dramatic duotone effect",
    imageCaption: "The inks agreed to share the portrait. Neither agreed to share the cleanup solvent.",
    keywords: ["duotone effect", "Ether-MOSH Duotone", "two color photo effect", "duotone printing", "gradient map", "motion graphics color", "projection visuals"],
    tldr: "The duotone effect maps an image's dark-to-light structure between two colors. Ether-MOSH measures luminance, builds a dark hue and a bright complementary hue, then blends that mapping with the source using Mix. Start at 0.80 Mix and 0.85 Hue. This is live RGB color mapping, not a print-ready two-ink separation.",
    satireDisclosure: "The ink mediation, press operator Lionel Split, and roller hostility are fictional. The duotone printing explanation, Ether-MOSH mapping behavior, accessibility guidance, and production advice are factual and sourced.",
    dispatch: [
      "At 09:37, fictional press operator Lionel Split called an emergency mediation between one indigo roller and one coral roller. Both claimed ownership of the highlights. The grayscale portrait sat between them wondering why creative direction always becomes family court.",
      "Split assigned the shadows to the darker ink, the highlights to the brighter one, and every midtone to a supervised blend. Mix signed the settlement. Hue immediately requested a transfer.",
    ],
    explanation: [
      "Adobe describes traditional duotones as grayscale images printed with two inks, often using one ink for darker values and another to extend or tint the tonal range. Each physical ink can have its own curve, and overprint behavior depends on ink, order, paper, and press conditions.",
      "Ether-MOSH borrows the two-color look but uses a different mechanism. Its shader calculates luminance, creates a dark saturated color from Hue, creates a bright color one-half turn around the hue wheel, and interpolates between them from shadow to highlight. Mix blends that mapped result over the original RGB image.",
      "Because the two colors may differ more in hue than lightness, do not use the effect alone to communicate status or meaning. W3C guidance says color should not be the only visual cue; preserve labels, shapes, or other structure and verify readable contrast separately.",
    ],
    steps: [
      "Load a portrait, product shot, landscape, or clip with a readable grayscale silhouette, then add Duotone from Color in the FX panel.",
      "Set Mix to 0.80 and Hue to 0.85. The source should keep its structure while the two-color mapping becomes unmistakable.",
      "Move Hue slowly to choose the dark color; Ether-MOSH automatically places the bright color opposite it on the hue wheel. Stop where both shadows and highlights remain distinct.",
      "Lower Mix toward 0.35–0.60 for a tinted photograph, or raise it toward 1 for a dominant two-color treatment. Keep essential text and interface cues outside the effected layer.",
      "Export and proof in the destination workflow. For a real two-ink print job, rebuild separations and curves with the printer instead of handing them an RGB frame and a confident shrug.",
    ],
    parameters: [
      { control: "Mix", purpose: "Blends the source with the two-color luminance map", low: "Subtle tint over source", high: "Mapped colors dominate", sweetSpot: "0.80" },
      { control: "Hue", purpose: "Chooses the dark hue; the bright hue sits opposite", low: "Moves around the hue wheel", high: "Completes one full hue cycle", sweetSpot: "0.85" },
      { control: "Source luminance", purpose: "Controls how the two colors divide across the image", low: "Flat light compresses separation", high: "Clear shadows and highlights read strongly", sweetSpot: "Distinct grayscale structure" },
    ],
    uses: [
      { title: "Print + editorial", body: "Use MOSH to audition color relationships quickly, then translate the chosen look into actual spot inks and curves for press. The preview inspires the separation; it is not the separation." },
      { title: "Pattern + merch", body: "Apply Duotone before building a repeat to unify mixed source material. Proof seams and physical scale, especially when the complementary pair creates a loud edge at every tile boundary." },
      { title: "Vector + Lottie", body: "Trace major luminance regions into two vector fills, or animate Hue slowly in a compact raster-backed loop. Preserve labels and icons as real vectors above the color treatment." },
      { title: "Projection + museum", body: "Use one strong silhouette and controlled Hue changes to compare color perception without changing geometry. Add captions or shape cues so the lesson never depends on color alone." },
    ],
    quote: "Duotone is not indecision. It is a strict two-party system with luminance counting the votes.",
    quoteAttribution: "Lionel Split, fictional mediator of incompatible inks",
    downloadHref: "/news/downloads/duotone-field-card.md",
    product: {
      name: "Digital Sunset Chevron Hoodie",
      href: "https://aestheticrebellion.store/products/digital-sunset-chevron-hoodie",
      copy: "This tutorial has been interrupted by the Digital Sunset Chevron Hoodie at aestheticrebellion.store, a crimson-and-cobalt pullover behaving like two colors won custody of the same sunset. It cannot separate spot inks. It can separate you from seventy dollars with admirable tonal discipline.",
    },
    sources: [
      { label: "Adobe — Use duotones in Photoshop", href: "https://helpx.adobe.com/photoshop/using/duotones.html", note: "Authoritative explanation of two-ink grayscale reproduction, ink curves, overprint, and press considerations." },
      { label: "W3C — Use of Color", href: "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color", note: "Current guidance that color should not be the only visual means of conveying information." },
      { label: "Ether-MOSH Duotone registry entry", href: "/effects#duotone", note: "Current Color category, Mix and Hue ranges, defaults, and shader source." },
      { label: "Halftone field report", href: "/news/halftone-is-not-a-phase-mom", note: "Related guide to print-inspired tonal reproduction and proofing." },
      { label: "Posterize field report", href: "/news/posterize-the-image-before-the-gradient-files-a-complaint", note: "Companion guide to reducing source tone into flat graphic regions." },
    ],
    relatedEffects: ["posterize", "halftone", "thermal", "noiseTint"],
    faqs: [
      { question: "What does the duotone effect do?", answer: "It maps image shadows and highlights between two colors while preserving the source's luminance structure." },
      { question: "Where is Duotone in Ether-MOSH?", answer: "Open the FX panel, choose Color, and add Duotone. Its controls are Mix and Hue, both ranging from 0–1." },
      { question: "What Duotone settings should I start with?", answer: "Start at 0.80 Mix and 0.85 Hue, then move Hue for the palette and lower Mix if you want more of the original color." },
      { question: "Is Ether-MOSH Duotone the same as two-ink printing?", answer: "No. It is an RGB luminance-to-color mapping inspired by the look. Real duotone printing requires separate inks, curves, overprint decisions, and press proofing." },
    ],
  },
  {
    slug: "make-ascii-collapse-admit-it-is-not-actually-text",
    subjectKind: "effect",
    effectId: "asciiCollapse",
    effectName: "ASCII Collapse",
    category: "Character Witness Protection",
    title: "Make ASCII Collapse Admit It Is Not Actually Text",
    dek: "The cells look typographic, the portrait looks nervous, and absolutely nobody has produced a character code despite several hours of aggressive terminal cosplay.",
    description: "Learn how the ASCII Collapse effect uses cell sampling and a luminance-shaped mask, plus practical Ether-MOSH Amount and Cell settings for motion, print, and projection.",
    publishedAt: "2026-09-01T09:38:00-07:00",
    readMinutes: 6,
    image: "/news/ascii-collapse-lab.jpg",
    imageAlt: "A fictional computer technician watches a portrait break into abstract glyph-like cells during an ASCII Collapse effect experiment in a retro laboratory",
    imageCaption: "The terminal produced fourteen feet of evidence and zero selectable characters.",
    keywords: ["ASCII Collapse effect", "Ether-MOSH ASCII Collapse", "ASCII art effect", "glyph quantization", "cell sampling", "retro computer graphics", "VJ effects"],
    tldr: "ASCII Collapse samples the image in square cells and replaces continuous detail with a luminance-shaped graphic mask. Amount controls the blend; Cell sets a 4–40 pixel grid size. It is ASCII-inspired, not literal ASCII: the shader emits no character codes or selectable text. Start at 0.70 Amount and 12 Cell.",
    satireDisclosure: "The laboratory, technician Vera Terminal, paper-trail investigation, and character-code confession are fictional. The ASCII standard, computer-art history, Ether-MOSH shader distinction, accessibility guidance, and production advice are factual and sourced.",
    dispatch: [
      "At 09:38, fictional technician Vera Terminal placed a portrait under observation and increased Cell to twelve. The face immediately broke into blocky marks, the paper terminal began vomiting evidence, and three executives described the incident as ‘basically the Matrix’ before being removed for technical misconduct.",
      "Terminal searched the output for actual characters. There were none. Amount had blended the source with a brightness-shaped mask, Cell had enlarged the grid, and the effect finally admitted it had been wearing typographic clothing without a text license.",
    ],
    explanation: [
      "ASCII is a real character-encoding standard. RFC 20 documented standard seven-bit ASCII for network interchange in 1969, with coded positions for control and graphic characters. That history concerns interoperable text symbols, not an automatic recipe for turning photographs into art.",
      "Computer artists were already exploring programmed images and text-like forms in the same era. The Computer History Museum documents Ken Knowlton's BEFLIX system at Bell Labs, a 252 by 184 dot field with eight gray levels, and collaborations including Stan VanDerBeek's word-centered Poemfields. Those works help explain why coarse grids, limited tone, and glyphs remain powerful visual language.",
      "Ether-MOSH ASCII Collapse is deliberately an impression, not an encoder. It samples one source color at each Cell-sized block, measures luminance, draws an abstract bar-like mask inside the block, and blends that result with Amount. It never selects an ASCII character, creates a DOM text node, or makes the image readable to assistive technology.",
      "If the source contains meaningful words, keep real text or captions outside the effect. W3C guidance requires sufficient contrast for text and images of text; an abstract glyph texture should remain decorative unless the same information is available in an accessible form.",
    ],
    steps: [
      "Load a high-contrast face, object, logo-free symbol, or clip, then add ASCII Collapse from Data Corruption in the FX panel.",
      "Set Amount to 0.70 and Cell to 12. This reveals the grid and mask while leaving enough source structure to recognize the subject.",
      "Lower Cell toward 6–10 for finer detail, or raise it toward 18–28 for bold stage-readable blocks. The full range is 4–40 pixels.",
      "Lower Amount for a textured overlay or raise it toward 1 for the strongest collapse. At 0, the source remains unchanged; no typographic alibi is required.",
      "Export a still or short loop, then check recognition at thumbnail and venue distance. Keep titles, captions, instructions, and accessibility text as real content outside the effected image.",
    ],
    parameters: [
      { control: "Amount", purpose: "Blends the original image with the glyph-like mask", low: "Source stays intact", high: "Masked cells dominate", sweetSpot: "0.70" },
      { control: "Cell", purpose: "Sets the sampled grid size in pixels", low: "4–10 fine detail", high: "24–40 large blocks", sweetSpot: "12" },
      { control: "Source contrast", purpose: "Determines how clearly luminance shapes each cell", low: "Flat regions merge", high: "Strong edges remain legible", sweetSpot: "Simple silhouette" },
    ],
    uses: [
      { title: "Print + editorial", body: "Freeze a frame with a recognizable silhouette and print it large enough for the cell structure to survive. Do not mistake decorative marks for readable copy; typeset the actual headline separately." },
      { title: "Pattern + textiles", body: "Crop a strong cell field and tile it as abstract texture. Proof the repeat so rows do not accidentally align into a barcode that starts demanding inventory access." },
      { title: "Vector + Lottie", body: "Trace a limited set of large cell shapes into vectors or use a short raster loop behind lightweight labels. Preserve every meaningful word as real text in the final experience." },
      { title: "Projection + museum", body: "Animate Amount slowly or compare Cell sizes beside RFC 20 and early computer-art material. Explain that the visual resemblance to text is intentional while the implementation is not character encoding." },
    ],
    quote: "Looking like text is not the same as being text. Ask any terms-of-service screenshot.",
    quoteAttribution: "Vera Terminal, fictional examiner of suspicious glyphs",
    downloadHref: "/news/downloads/ascii-collapse-field-card.md",
    product: {
      name: "Gadget Pop AOP Body Pillow",
      href: "https://aestheticrebellion.store/products/gadget-pop-aop-body-pillow",
      copy: "The Gadget Pop AOP Body Pillow at aestheticrebellion.store has entered the evidence room carrying retro technology collage across an extremely long cushion. It cannot encode ASCII, compile software, or improve Cell. It can make your sofa look like a mainframe developed emotional-support hardware.",
    },
    sources: [
      { label: "IETF — RFC 20: ASCII format for network interchange", href: "https://datatracker.ietf.org/doc/html/rfc20", note: "Primary 1969 network document reproducing the seven-bit ASCII standard and code table." },
      { label: "Computer History Museum — Technology + Art", href: "https://computerhistory.org/exhibits/technology-art/", note: "Museum history of Bell Labs computer graphics, BEFLIX, Poemfields, and early programmed art." },
      { label: "W3C — Contrast (Minimum)", href: "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html", note: "Current guidance for readable text and images of text." },
      { label: "Ether-MOSH ASCII Collapse registry entry", href: "/effects#asciiCollapse", note: "Current Data Corruption category, Amount and Cell ranges, defaults, and shader source." },
      { label: "CRT field report", href: "/news/your-fake-crt-looks-cheap", note: "Related guide to historically informed display texture and venue use." },
      { label: "Datamosh field report", href: "/news/break-the-keyframes-before-lunch", note: "Companion guide to separating a visual reference from the mechanism that actually creates it." },
    ],
    relatedEffects: ["bitCrush", "crtPhosphor", "datamosh", "pixelSort"],
    faqs: [
      { question: "Is ASCII Collapse creating real ASCII text?", answer: "No. It samples image cells and draws a luminance-shaped mask. It emits no character codes, selectable text, or accessible text content." },
      { question: "Where is ASCII Collapse in Ether-MOSH?", answer: "Open the FX panel, choose Data Corruption, and add ASCII Collapse. Its controls are Amount from 0–1 and Cell from 4–40 pixels." },
      { question: "What ASCII Collapse settings should I start with?", answer: "Start at 0.70 Amount and 12 Cell. Lower Cell for more detail or raise it for larger blocks that survive projection distance." },
      { question: "Can I use ASCII Collapse on typography?", answer: "You can use it decoratively, but keep meaningful words as real text or provide an equivalent caption because the effected result is only pixels." },
    ],
  },
  {
    slug: "make-the-solarize-effect-expose-itself",
    subjectKind: "effect",
    effectId: "solarize",
    effectName: "Solarize",
    category: "Darkroom Misconduct",
    title: "Make the Solarize Effect Expose Itself",
    dek: "A bright region crossed the Pivot, reversed its testimony, and left the darkroom insisting this was absolutely how color channels have always behaved.",
    description: "Learn how the Solarize effect selectively inverts RGB channels and how to set Ether-MOSH Amount and Pivot for print, motion, projection, patterns, and education.",
    publishedAt: "2026-09-02T12:23:00-07:00",
    readMinutes: 6,
    image: "/news/solarize-darkroom-incident.jpg",
    imageAlt: "A fictional darkroom Solarize effect incident with two masked technicians beside a large portrait whose black-and-white tones are partially reversed",
    imageCaption: "The fictional tone-reversal unit has secured the trays. The highlights have retained separate counsel.",
    keywords: ["Solarize effect", "Ether-MOSH Solarize", "photo solarization", "Sabattier effect", "digital darkroom effect", "VJ color effects", "solarized photography"],
    tldr: "Ether-MOSH's Solarize effect selectively inverts each RGB channel when that channel rises above Pivot, then blends the result with Amount. Pivot decides which channel values flip; Amount decides how forcefully the altered color replaces the source. It is a fast digital echo of photographic solarization, not a chemical Sabattier process, and it lives under Color.",
    satireDisclosure: "The tone-reversal unit, technicians, hearing, and disobedient highlights are fictional. The photographic history, Lee Miller and Man Ray attribution, Ether-MOSH controls and shader behavior, accessibility guidance, and production advice are factual and sourced.",
    dispatch: [
      "At 12:23, fictional Deputy Curator Hal Negative raised Pivot to 0.52. Every bright channel in the evidence portrait immediately reversed its story while the shadows sat perfectly still, looking smug and underexposed.",
      "The fictional Darkroom Standards Board blamed sunlight, chemistry, and a technician named Gary. None were present. This was a GPU shader with two controls, but the board had already ordered tiny badges and refused to cancel the hearing.",
    ],
    explanation: [
      "Photographic terminology is messier than the myth. Getty's Art & Architecture Thesaurus distinguishes the Sabattier effect—partial positive/negative reversal caused by strong light during development—from true solarization caused by extreme overexposure at capture. In everyday art history, the darkroom result is still commonly called solarization or pseudo-solarization.",
      "MoMA describes darkroom solarization as a second flash of light interrupting development, producing a hybrid positive-and-negative image with exaggerated high-contrast borders and sometimes a metallic appearance. The Metropolitan Museum of Art credits Lee Miller's accidental rediscovery of the phenomenon, which she shared with Man Ray; they refined it together, and Man Ray named their treatment ‘solarization.’",
      "Ether-MOSH does not simulate emulsion, developer, or the bright boundary line chemically. Its Solarize shader compares red, green, and blue separately with Pivot, inverts only the channel values above that point, then blends the result with Amount. Because the renderer currently gives Amount a 2× gain, the visible slider reaches a complete blend around 0.50; higher values drive a harder, clipped digital blowout rather than a more authentic darkroom print.",
      "A still Solarize frame does not flash by itself. Rapidly automating Pivot or Amount can create large opposing luminance changes, especially on projection. W3C guidance says flashing content must not exceed three flashes in any one-second period unless it stays below defined thresholds. Move the controls slowly, test the largest display, and keep captions or instructions outside the effected image.",
    ],
    steps: [
      "Open MOSH, load a hard-lit portrait, product still, architectural detail, or clip, then add Solarize from Color in the FX panel.",
      "Set Amount to 0.35 and Pivot to 0.52. The current render gain makes this a clear partial reversal without immediately crushing the frame.",
      "Sweep Pivot between roughly 0.35 and 0.65. Lower values flip more channel data; higher values reserve the reversal for brighter channel values.",
      "Raise Amount toward 0.50 for a complete digital blend. Go above 0.50 only when you want the exaggerated clipping, then try Posterize or Film Grain after Solarize for graphic bands or texture.",
      "Export a still for print, or animate one control slowly for motion. Check skin, gradients, readable words, and full-screen flash behavior before the file reaches a shirt, stage, classroom, or unsuspecting museum wall.",
    ],
    parameters: [
      { control: "Amount", purpose: "Controls how strongly the selectively inverted color replaces the source", low: "0–0.25 subtle", high: "0.65–1 hard clipping", sweetSpot: "0.35" },
      { control: "Pivot", purpose: "Sets the per-channel value above which red, green, or blue inverts", low: "0.15 flips more", high: "0.85 flips highlights", sweetSpot: "0.52" },
      { control: "Source contrast", purpose: "Determines how clearly the reversal separates forms", low: "Flat, broad color shifts", high: "Sharp tonal boundaries", sweetSpot: "Hard side light" },
    ],
    uses: [
      { title: "Print + editorial", body: "Freeze a restrained reversal, soft-proof the inverted colors, and inspect gradients at 100%. The screen can invent electric color that a four-color press will translate into something more municipal." },
      { title: "Pattern + textiles", body: "Solarize one motif before building the repeat, then inspect a 3×3 proof. Reversed highlights make useful rhythm, but a clipped edge repeated sixty times becomes a labor dispute." },
      { title: "Vector + Lottie", body: "Trace the strongest reversed boundaries into a small vector palette, or use a short raster loop behind lightweight Lottie shapes. Keep meaningful text as real text rather than solarized pixels." },
      { title: "Projection + venue", body: "Use a slow Pivot sweep across faces, flowers, or architecture and test it at full venue scale. Avoid rapid high-contrast oscillation; a giant wall is not the place to discover your loop became a strobe." },
      { title: "Museum + education", body: "Place a documented darkroom solarization beside the same source treated in Ether-MOSH. Students can compare a chemical positive/negative hybrid with a modern per-channel threshold shader without pretending the mechanisms are identical." },
    ],
    quote: "The highlight did not disappear. It changed sides and started dressing like a negative.",
    quoteAttribution: "Hal Negative, fictional deputy curator of reversible testimony",
    downloadHref: "/news/downloads/solarize-field-card.md",
    product: {
      name: "Boundless Bleeds UV Arm Sleeves",
      href: "https://aestheticrebellion.store/products/boundless-bleeds-uv-arm-sleeves",
      copy: "Obvious commercial interruption: Aesthetic Rebellion's Boundless Bleeds UV Arm Sleeves are paint-splattered, UPF-rated, and currently available for purchase. They protect arms from actual sunlight, which is not what this shader means by Solarize, but accuracy has never stopped an accessory from entering the syllabus.",
    },
    sources: [
      { label: "Getty Research — Sabattier effect", href: "https://vocab.getty.edu/page/aat/300135014", note: "Authoritative terminology, early history, and the distinction between development-time reversal and true exposure solarization." },
      { label: "MoMA Object:Photo — Materials glossary", href: "https://www.moma.org/interactives/objectphoto/materials/glossary.html", note: "Museum explanation of the second exposure, hybrid positive/negative image, border emphasis, and metallic appearance." },
      { label: "The Met — An Overlooked Partnership", href: "https://www.metmuseum.org/perspectives/man-ray-lee-miller", note: "Current museum account crediting Lee Miller's rediscovery and the process she refined with Man Ray." },
      { label: "W3C — Three Flashes or Below Threshold", href: "https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold.html", note: "Current accessibility guidance for animated high-contrast changes and flash thresholds." },
      { label: "Ether-MOSH Solarize registry entry", href: "/effects#solarize", note: "Current Color category, Amount and Pivot ranges, defaults, render gain, and shader source." },
      { label: "Posterize field report", href: "/news/posterize-the-image-before-the-gradient-files-a-complaint", note: "Related guide to deliberate tonal clipping, print proofing, and graphic reduction." },
      { label: "Duotone field report", href: "/news/make-the-duotone-effect-pick-a-side", note: "Companion guide to luminance-based color mapping and print-inspired RGB workflows." },
    ],
    relatedEffects: ["posterize", "duotone", "photocopy", "crtPhosphor"],
    faqs: [
      { question: "What does the Solarize effect do in Ether-MOSH?", answer: "It inverts each RGB channel only when that channel's value is above Pivot, then blends the changed color with the source using Amount." },
      { question: "Is Ether-MOSH Solarize the same as darkroom solarization?", answer: "No. The app uses a real-time per-channel threshold shader. Darkroom solarization or the Sabattier effect interrupts chemical development with another exposure to light." },
      { question: "Where is Solarize, and what settings should I start with?", answer: "Open the FX panel, choose Color, and add Solarize. Start near 0.35 Amount and 0.52 Pivot, then tune Pivot for the source's highlights." },
      { question: "Can I animate the Solarize effect safely for projection?", answer: "Yes, but move Amount or Pivot slowly and test the full-size output. Do not create more than three high-contrast flashes per second unless the result is verified below the applicable thresholds." },
    ],
  },
];

export const NEWS_ARTICLES_BY_SLUG = new Map(NEWS_ARTICLES.map((article) => [article.slug, article]));
export const latestNewsArticles = [...NEWS_ARTICLES].sort((a, b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt));
export const newsArticlePath = (article: NewsArticle) => `/news/${article.slug}`;

export const NEWS_LOOK_EXAMPLES_BY_SLUG: Record<string, [NewsLookExample, NewsLookExample]> = {
  "sort-your-pixels-before-they-sort-you": [
    { scene: "High-contrast portrait", settings: "Amount 0.30 · Threshold 0.62", result: "Bright skin, hair, and catchlights pull into thin horizontal rails while the dark jawline and background remain recognizable." },
    { scene: "Night skyline", settings: "Amount 0.58 · Threshold 0.38", result: "Windows and streetlights stretch into long luminous bands; the darker buildings stay behind as hard anchors." },
  ],
  "halftone-is-not-a-phase-mom": [
    { scene: "Soft-lit face", settings: "Amount 0.45 · Dot Size 0.22", result: "Midtones become a fine printed screen. Eyes, mouth, and the edge of the nose still read from thumbnail distance." },
    { scene: "Bold poster artwork", settings: "Amount 0.80 · Dot Size 0.65", result: "Gradients turn into oversized circles and flat color fields; the dots become the composition instead of surface texture." },
  ],
  "make-moire-before-moire-makes-you-sick": [
    { scene: "Simple silhouette", settings: "Amount 0.22 · Pitch 0.30", result: "Wide interference bands drift across the subject like a slow topographic wave, with plenty of the source left visible." },
    { scene: "Geometric artwork", settings: "Amount 0.62 · Pitch 0.72", result: "Two dense grids beat against each other, producing tight moving ripples that look much larger than either source grid." },
  ],
  "break-the-keyframes-before-lunch": [
    { scene: "Dancer crossing frame", settings: "Amount 0.35 · Block Size 0.020", result: "Hands and shoulders leave small rectangular echoes while the still background remains mostly locked in place." },
    { scene: "Fast camera pan", settings: "Amount 0.68 · Block Size 0.040", result: "The frame breaks into broad slabs that drag old color and shape into the new view, like motion borrowing the wrong image." },
  ],
  "your-fake-crt-looks-cheap": [
    { scene: "Portrait or interview", settings: "Curvature 0.22 · Mask 0.35 · Bloom 0.18", result: "The picture bows gently at the corners, fine RGB texture sits on the surface, and highlights glow without swallowing facial detail." },
    { scene: "Logo or neon title", settings: "Curvature 0.48 · Mask 0.65 · Bloom 0.42", result: "Edges bend into obvious tube geometry, the phosphor grille becomes visible, and bright lettering spills a soft colored halo." },
  ],
  "forge-mode-already-started-the-fight": [
    { scene: "Held procedural composition", settings: "Intensity 0.42 · Hold a strong seed", result: "Sparse geometric forms keep clear negative space and repeatable structure—useful for a print still or a restrained loop." },
    { scene: "Audio-reactive performance", settings: "Intensity 0.72 · Evolution active", result: "Denser generated forms, color fields, and effect stacks trade places on the beat, creating a full moving visual without source footage." },
  ],
  "stop-gaslighting-the-seam": [
    { scene: "Single bold motif", settings: "Mirror symmetry · Low density", result: "The subject reflects cleanly across each tile edge, producing a calm repeat with obvious breathing room and no hard seam." },
    { scene: "Textured camera still", settings: "Kaleidoscope symmetry · High density", result: "Small fragments rotate into a crowded radial fabric-like field; the 3×3 proof reveals the larger repeat rhythm." },
  ],
  "turn-the-kaleidoscope-effect-until-it-confesses": [
    { scene: "Off-center portrait", settings: "6 Segments · Spin 0.15", result: "Eyes, cheekbones, and clothing repeat as six mirrored petals; the face remains recognizable but becomes a rotating radial emblem." },
    { scene: "Architectural detail", settings: "12 Segments · Spin 0.05", result: "Windows and hard edges multiply into dense lace-like symmetry with a slow, almost mechanical turn." },
  ],
  "posterize-the-image-before-the-gradient-files-a-complaint": [
    { scene: "Hard-lit portrait", settings: "5 Levels · Bias 0.50", result: "Smooth cheek and forehead gradients snap into flat color zones, with crisp borders around the eyes, nose, and hair." },
    { scene: "Landscape at dusk", settings: "3 Levels · Bias 0.35", result: "Clouds and hills collapse into bold shadow shapes while the sky becomes a small stack of graphic color bands." },
  ],
  "make-the-duotone-effect-pick-a-side": [
    { scene: "Black-and-white portrait", settings: "Mix 0.80 · Hue 0.85", result: "Shadows take the selected deep hue and highlights swing toward its opposite, preserving the face as a sharp two-color luminance map." },
    { scene: "Concrete architecture", settings: "Mix 0.45 · Hue 0.55", result: "Original color remains underneath a restrained cool-versus-warm split, so windows and structural shadows gain graphic separation." },
  ],
  "make-ascii-collapse-admit-it-is-not-actually-text": [
    { scene: "High-contrast face", settings: "Amount 0.70 · Cell 12", result: "The face resolves through square samples and bar-like marks; dark eye cells and bright forehead cells preserve recognition without real letters." },
    { scene: "Full-body silhouette", settings: "Amount 1.00 · Cell 28", result: "Large glyph-like blocks replace fine detail, turning the figure into a coarse terminal-flavored mosaic that reads best from a distance." },
  ],
  "make-the-solarize-effect-expose-itself": [
    { scene: "Hard-lit portrait", settings: "Amount 0.35 · Pivot 0.52", result: "Bright skin and fabric channels reverse into cool negative color while the deepest shadows remain anchored, leaving the face readable inside a sharp tonal split." },
    { scene: "Saturated flower still", settings: "Amount 0.48 · Pivot 0.38", result: "Petals break into acidic complementary bands, bright edges harden, and the background keeps enough original color to frame the reversal." },
  ],
};
