// Originally generated by Lovable. Hand-edited since: this build no longer uses
// Lovable's auth broker, and session persistence needed hardening it did not do.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/**
 * Storage that cannot throw.
 *
 * `storage: localStorage` was passed directly, which is fine right up until it
 * isn't: Safari private mode, iOS lockdown, embedded webviews and blocked
 * third-party storage all make localStorage present-but-throwing. Supabase then
 * silently falls back to in-memory storage, which works perfectly for the rest
 * of the tab's life and loses the session on every refresh — exactly the
 * symptom, and one that never reproduces for whoever is debugging it.
 *
 * Probing once at startup and degrading deliberately means the failure is at
 * least visible in the console instead of looking like a random sign-out.
 */
function safeStorage(): Storage {
  try {
    const probe = '__mosh_probe__';
    window.localStorage.setItem(probe, '1');
    window.localStorage.removeItem(probe);
    return window.localStorage;
  } catch {
    console.warn(
      '[mosh] localStorage is unavailable — sign-in will not survive a refresh. ' +
      'Usually private browsing or blocked site data.',
    );
    const mem = new Map<string, string>();
    return {
      getItem: (k) => mem.get(k) ?? null,
      setItem: (k, v) => { mem.set(k, String(v)); },
      removeItem: (k) => { mem.delete(k); },
      clear: () => mem.clear(),
      key: (i) => Array.from(mem.keys())[i] ?? null,
      get length() { return mem.size; },
    } as Storage;
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage(),
    // A fixed key rather than one derived from the project URL: a derived key
    // changes if the URL ever does, and every existing session silently
    // disappears at once.
    storageKey: 'mosh-auth',
    persistSession: true,
    autoRefreshToken: true,
    // The dedicated /auth/callback route exchanges PKCE codes explicitly.
    // Keeping automatic URL detection off prevents a second exchange racing it.
    detectSessionInUrl: false,
    /**
     * PKCE rather than implicit.
     *
     * Implicit returns tokens in the URL *fragment*, which anything that
     * rewrites location — a router, a history.replaceState, a redirect — can
     * destroy before Supabase reads it, losing the session at the moment it was
     * created. PKCE returns a short-lived code exchanged over the network
     * instead, so the tokens never ride in the URL and cannot be wiped by
     * navigation. It also keeps access tokens out of browser history.
     */
    flowType: 'pkce',
  },
});
